import { UniverseArtist } from './artistUniverse';

export const ARTIST_UNIVERSE_EXTENSION: UniverseArtist[] = [
  // ==========================================
  // 1. POP / GLOBAL HITS / DANCE-POP / K-POP
  // ==========================================
  { name: 'BTS', targetCount: 22, genre: 'Pop' },
  { name: 'BLACKPINK', targetCount: 20, genre: 'Pop' },
  { name: 'Jung Kook', searchQuery: 'Jung Kook', targetCount: 12, genre: 'Pop' },
  { name: 'Jimin', targetCount: 10, genre: 'Pop' },
  { name: 'LISA', searchQuery: 'LISA BLACKPINK', targetCount: 8, genre: 'Pop' },
  { name: 'NewJeans', targetCount: 12, genre: 'Pop' },
  { name: 'TWICE', targetCount: 16, genre: 'Pop' },
  { name: 'Stray Kids', targetCount: 16, genre: 'Pop' },
  { name: 'LE SSERAFIM', targetCount: 12, genre: 'Pop' },
  { name: 'IVE', targetCount: 12, genre: 'Pop' },
  { name: 'aespa', targetCount: 12, genre: 'Pop' },
  { name: 'FIFTY FIFTY', targetCount: 6, genre: 'Pop' },
  { name: 'PSY', targetCount: 10, genre: 'Pop' },
  { name: 'Ava Max', targetCount: 16, genre: 'Pop' },
  { name: 'Meghan Trainor', targetCount: 16, genre: 'Pop' },
  { name: 'Jessie J', targetCount: 14, genre: 'Pop' },
  { name: 'Carly Rae Jepsen', targetCount: 16, genre: 'Pop' },
  { name: 'Kelly Clarkson', targetCount: 20, genre: 'Pop' },
  { name: 'Ashlee Simpson', targetCount: 8, genre: 'Pop' },
  { name: 'Jessica Simpson', targetCount: 8, genre: 'Pop' },
  { name: 'Mandy Moore', targetCount: 8, genre: 'Pop' },
  { name: 'Leona Lewis', targetCount: 12, genre: 'Pop' },
  { name: 'Alexandra Burke', targetCount: 8, genre: 'Pop' },
  { name: 'Cheryl', searchQuery: 'Cheryl Cole', targetCount: 8, genre: 'Pop' },
  { name: 'Girls Aloud', targetCount: 12, genre: 'Pop' },
  { name: 'Sugababes', targetCount: 14, genre: 'Pop' },
  { name: 'Atomic Kitten', targetCount: 8, genre: 'Pop' },
  { name: 'S Club 7', targetCount: 10, genre: 'Pop' },
  { name: 'Steps', targetCount: 10, genre: 'Pop' },
  { name: 'Westlife', targetCount: 18, genre: 'Pop' },
  { name: 'Boyzone', targetCount: 12, genre: 'Pop' },
  { name: 'Take That', targetCount: 18, genre: 'Pop' },
  { name: 'Robbie Williams', targetCount: 22, genre: 'Pop' },
  { name: 'Gary Barlow', targetCount: 8, genre: 'Pop' },
  { name: 'Olly Murs', targetCount: 14, genre: 'Pop' },
  { name: 'Mika', targetCount: 12, genre: 'Pop' },
  { name: 'Scissor Sisters', targetCount: 10, genre: 'Pop' },
  { name: 'The Pussycat Dolls', targetCount: 14, genre: 'Pop' },
  { name: 'Nicole Scherzinger', targetCount: 10, genre: 'Pop' },
  { name: 'All Saints', targetCount: 10, genre: 'Pop' },
  { name: 'Corinne Bailey Rae', targetCount: 8, genre: 'R&B/Soul' },
  { name: 'Dido', targetCount: 14, genre: 'Pop' },
  { name: 'Natalie Imbruglia', targetCount: 10, genre: 'Pop' },
  { name: 'Alanis Morissette', targetCount: 18, genre: 'Rock' },
  { name: 'Sheryl Crow', targetCount: 16, genre: 'Rock' },
  { name: 'Fiona Apple', targetCount: 12, genre: 'Alternative' },
  { name: 'Tori Amos', targetCount: 12, genre: 'Alternative' },
  { name: 'Jewel', targetCount: 12, genre: 'Pop' },
  { name: 'Sarah McLachlan', targetCount: 12, genre: 'Pop' },
  { name: 'Paula Cole', targetCount: 6, genre: 'Pop' },
  { name: 'Meredith Brooks', targetCount: 6, genre: 'Rock' },
  { name: 'Joan Osborne', targetCount: 6, genre: 'Rock' },
  { name: 'Shawn Colvin', targetCount: 6, genre: 'Pop' },
  { name: 'Tracy Chapman', targetCount: 14, genre: 'Pop' },
  { name: 'Suzanne Vega', targetCount: 8, genre: 'Pop' },

  // ==========================================
  // 2. HIP-HOP & RAP EXPANSION
  // ==========================================
  { name: 'Three 6 Mafia', targetCount: 16, genre: 'Hip-Hop/Rap' },
  { name: 'Juicy J', targetCount: 16, genre: 'Hip-Hop/Rap' },
  { name: 'Project Pat', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Master P', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Mystikal', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'Juvenile', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'Mannie Fresh', targetCount: 8, genre: 'Hip-Hop/Rap' },
  { name: 'Birdman', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Lil Flip', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'Slim Thug', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'Webbie', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'Boosie Badazz', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'Plies', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Young Dro', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'Rich Boy', targetCount: 6, genre: 'Hip-Hop/Rap' },
  { name: 'Shawty Lo', targetCount: 8, genre: 'Hip-Hop/Rap' },
  { name: 'Yung Joc', targetCount: 8, genre: 'Hip-Hop/Rap' },
  { name: 'Dem Franchize Boyz', targetCount: 8, genre: 'Hip-Hop/Rap' },
  { name: 'D4L', targetCount: 6, genre: 'Hip-Hop/Rap' },
  { name: 'Bobby Shmurda', targetCount: 8, genre: 'Hip-Hop/Rap' },
  { name: 'Rowdy Rebel', targetCount: 8, genre: 'Hip-Hop/Rap' },
  { name: 'Fivio Foreign', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Sheff G', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'Sleepy Hallow', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'CJ', targetCount: 6, genre: 'Hip-Hop/Rap' },
  { name: 'SpotemGottem', targetCount: 6, genre: 'Hip-Hop/Rap' },
  { name: 'Cochise', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'Ken Carson', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'Destroy Lonely', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'Homixide Gang', targetCount: 8, genre: 'Hip-Hop/Rap' },
  { name: 'Yeat', targetCount: 18, genre: 'Hip-Hop/Rap' },
  { name: 'SoFaygo', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'BabyTron', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Rio Da Yung OG', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'EST Gee', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: '42 Dugg', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'Moneybagg Yo', targetCount: 18, genre: 'Hip-Hop/Rap' },
  { name: 'Yo Gotti', targetCount: 16, genre: 'Hip-Hop/Rap' },
  { name: 'Blac Youngsta', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'Key Glock', targetCount: 16, genre: 'Hip-Hop/Rap' },
  { name: 'Young Dolph', targetCount: 18, genre: 'Hip-Hop/Rap' },
  { name: 'Pooh Shiesty', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Big30', targetCount: 8, genre: 'Hip-Hop/Rap' },
  { name: 'Duke Deuce', targetCount: 8, genre: 'Hip-Hop/Rap' },
  { name: 'Nardo Wick', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'Morray', targetCount: 8, genre: 'Hip-Hop/Rap' },
  { name: 'Tee Grizzley', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'Sada Baby', targetCount: 10, genre: 'Hip-Hop/Rap' },

  // ==========================================
  // 3. R&B & SOUL CLASSICS
  // ==========================================
  { name: 'Jodeci', targetCount: 14, genre: 'R&B/Soul' },
  { name: 'K-Ci & JoJo', searchQuery: 'K-Ci and JoJo', targetCount: 10, genre: 'R&B/Soul' },
  { name: 'Tevin Campbell', targetCount: 10, genre: 'R&B/Soul' },
  { name: 'Keith Sweat', targetCount: 14, genre: 'R&B/Soul' },
  { name: 'Johnny Gill', targetCount: 10, genre: 'R&B/Soul' },
  { name: 'Bobby Brown', targetCount: 12, genre: 'R&B/Soul' },
  { name: 'New Edition', targetCount: 14, genre: 'R&B/Soul' },
  { name: 'Bell Biv DeVoe', targetCount: 10, genre: 'R&B/Soul' },
  { name: 'Jon B.', searchQuery: 'Jon B', targetCount: 10, genre: 'R&B/Soul' },
  { name: 'Tamia', targetCount: 12, genre: 'R&B/Soul' },
  { name: 'SWV', targetCount: 12, genre: 'R&B/Soul' },
  { name: 'Xscape', targetCount: 10, genre: 'R&B/Soul' },
  { name: 'Total', targetCount: 8, genre: 'R&B/Soul' },
  { name: '702', targetCount: 8, genre: 'R&B/Soul' },
  { name: 'Blaque', targetCount: 6, genre: 'R&B/Soul' },
  { name: 'En Vogue', targetCount: 14, genre: 'R&B/Soul' },
  { name: 'Jade', targetCount: 6, genre: 'R&B/Soul' },
  { name: 'Changing Faces', targetCount: 6, genre: 'R&B/Soul' },
  { name: 'Donell Jones', targetCount: 10, genre: 'R&B/Soul' },
  { name: 'Joe', targetCount: 14, genre: 'R&B/Soul' },
  { name: 'Carl Thomas', targetCount: 8, genre: 'R&B/Soul' },
  { name: 'Avant', targetCount: 10, genre: 'R&B/Soul' },
  { name: 'Tank', targetCount: 12, genre: 'R&B/Soul' },
  { name: 'Lloyd', targetCount: 12, genre: 'R&B/Soul' },
  { name: 'Pretty Ricky', targetCount: 10, genre: 'R&B/Soul' },
  { name: 'Bobby V.', searchQuery: 'Bobby Valentino', targetCount: 10, genre: 'R&B/Soul' },
  { name: 'Ray J', targetCount: 8, genre: 'R&B/Soul' },
  { name: 'Mario Winans', targetCount: 6, genre: 'R&B/Soul' },
  { name: 'Ryan Leslie', targetCount: 8, genre: 'R&B/Soul' },
  { name: 'Cassie', targetCount: 8, genre: 'R&B/Soul' },
  { name: 'Kandi', targetCount: 6, genre: 'R&B/Soul' },
  { name: 'Lumidee', targetCount: 6, genre: 'R&B/Soul' },
  { name: 'Nina Sky', targetCount: 6, genre: 'Pop' },
  { name: 'Kat DeLuna', targetCount: 6, genre: 'Pop' },

  // ==========================================
  // 4. LATIN & REGIONAL MEXICAN & TROPICAL
  // ==========================================
  { name: 'Juan Luis Guerra', targetCount: 16, genre: 'Latin' },
  { name: 'Elvis Crespo', targetCount: 10, genre: 'Latin' },
  { name: 'Jerry Rivera', targetCount: 10, genre: 'Latin' },
  { name: 'Frankie Ruiz', targetCount: 10, genre: 'Latin' },
  { name: 'Celia Cruz', targetCount: 14, genre: 'Latin' },
  { name: 'Gilberto Santa Rosa', targetCount: 12, genre: 'Latin' },
  { name: 'Victor Manuelle', targetCount: 12, genre: 'Latin' },
  { name: 'Los Bukis', targetCount: 14, genre: 'Latin' },
  { name: 'Marco Antonio Solís', searchQuery: 'Marco Antonio Solis', targetCount: 16, genre: 'Latin' },
  { name: 'Los Tigres del Norte', targetCount: 16, genre: 'Latin' },
  { name: 'Los Tucanes de Tijuana', targetCount: 14, genre: 'Latin' },
  { name: 'Intocable', targetCount: 14, genre: 'Latin' },
  { name: 'Duelo', targetCount: 12, genre: 'Latin' },
  { name: 'Pesado', targetCount: 12, genre: 'Latin' },
  { name: 'La Arrolladora Banda El Limón', searchQuery: 'La Arrolladora Banda El Limon', targetCount: 14, genre: 'Latin' },
  { name: 'Banda El Recodo', targetCount: 14, genre: 'Latin' },
  { name: 'Gerardo Ortiz', targetCount: 14, genre: 'Latin' },
  { name: 'Los Dos Carnales', targetCount: 12, genre: 'Latin' },
  { name: 'Marca MP', targetCount: 12, genre: 'Latin' },
  { name: 'Tito Double P', targetCount: 10, genre: 'Latin' },
  { name: 'Gabito Ballesteros', targetCount: 12, genre: 'Latin' },
  { name: 'Oscar Maydon', targetCount: 10, genre: 'Latin' },
  { name: 'Chino Pacas', targetCount: 10, genre: 'Latin' },
  { name: 'Calle 24', targetCount: 8, genre: 'Latin' },
  { name: 'Xavi', targetCount: 10, genre: 'Latin' },

  // ==========================================
  // 5. ROCK / PUNK / ALTERNATIVE CLASSICS
  // ==========================================
  { name: 'New Found Glory', targetCount: 12, genre: 'Rock' },
  { name: 'The Starting Line', targetCount: 8, genre: 'Rock' },
  { name: 'The Red Jumpsuit Apparatus', targetCount: 8, genre: 'Rock' },
  { name: 'Bowling for Soup', targetCount: 10, genre: 'Rock' },
  { name: 'Plain White T\'s', searchQuery: 'Plain White Ts', targetCount: 10, genre: 'Rock' },
  { name: 'Fountains of Wayne', targetCount: 6, genre: 'Rock' },
  { name: 'Wheatus', targetCount: 6, genre: 'Rock' },
  { name: 'Smash Mouth', targetCount: 12, genre: 'Rock' },
  { name: 'Sugar Ray', targetCount: 12, genre: 'Rock' },
  { name: 'Lit', targetCount: 8, genre: 'Rock' },
  { name: 'Alien Ant Farm', targetCount: 8, genre: 'Rock' },
  { name: 'The Darkness', targetCount: 8, genre: 'Rock' },
  { name: 'The Vines', targetCount: 8, genre: 'Rock' },
  { name: 'The Hives', targetCount: 10, genre: 'Rock' },
  { name: 'Jet', targetCount: 10, genre: 'Rock' },
  { name: 'Wolfmother', targetCount: 10, genre: 'Rock' },
  { name: 'Silversun Pickups', targetCount: 12, genre: 'Alternative' },
  { name: 'Band of Horses', targetCount: 12, genre: 'Alternative' },
  { name: 'Local Natives', targetCount: 10, genre: 'Alternative' },
  { name: 'Young the Giant', targetCount: 14, genre: 'Rock' },
  { name: 'Manchester Orchestra', targetCount: 12, genre: 'Rock' },
  { name: 'Thrice', targetCount: 12, genre: 'Rock' },
  { name: 'Coheed and Cambria', targetCount: 14, genre: 'Rock' },
  { name: 'Circa Survive', targetCount: 10, genre: 'Rock' },
  { name: 'Saosin', targetCount: 8, genre: 'Rock' },
  { name: 'Underoath', targetCount: 12, genre: 'Metal' },
  { name: 'The Used', targetCount: 14, genre: 'Rock' },
  { name: 'Story of the Year', targetCount: 10, genre: 'Rock' },
  { name: 'Silverstein', targetCount: 12, genre: 'Rock' },
  { name: 'Senses Fail', targetCount: 10, genre: 'Rock' },
  { name: 'Hawthorne Heights', targetCount: 8, genre: 'Rock' },
  { name: 'From First to Last', targetCount: 8, genre: 'Rock' },
  { name: 'Chiodos', targetCount: 8, genre: 'Rock' },
  { name: 'A Day to Remember', targetCount: 18, genre: 'Rock' },
  { name: 'I Prevail', targetCount: 14, genre: 'Metal' },
  { name: 'Spiritbox', targetCount: 12, genre: 'Metal' },
  { name: 'Architects', targetCount: 14, genre: 'Metal' },
  { name: 'Motionless In White', targetCount: 14, genre: 'Metal' },
  { name: 'Ice Nine Kills', targetCount: 12, genre: 'Metal' },
  { name: 'Beartooth', targetCount: 12, genre: 'Rock' },
  { name: 'Wage War', targetCount: 10, genre: 'Metal' },
  { name: 'Polaris', targetCount: 10, genre: 'Metal' },
  { name: 'The Amity Affliction', targetCount: 12, genre: 'Metal' },
  { name: 'We Came As Romans', targetCount: 12, genre: 'Metal' },
  { name: 'Memphis May Fire', targetCount: 12, genre: 'Metal' },
  { name: 'Crown The Empire', targetCount: 10, genre: 'Rock' },
  { name: 'Of Mice & Men', searchQuery: 'Of Mice and Men', targetCount: 12, genre: 'Metal' },
  { name: 'Black Veil Brides', targetCount: 14, genre: 'Rock' },
  { name: 'Escape The Fate', targetCount: 12, genre: 'Rock' },
  { name: 'Whitechapel', targetCount: 10, genre: 'Metal' },
  { name: 'Lorna Shore', targetCount: 10, genre: 'Metal' },
  { name: 'Slaughter to Prevail', targetCount: 8, genre: 'Metal' },
];
