export interface UniverseArtist {
  name: string;
  searchQuery?: string;
  genre: 'Pop' | 'Hip-Hop/Rap' | 'R&B/Soul' | 'Dance' | 'Rock' | 'Latin' | 'Metal' | 'Alternative' | 'Country';
  targetCount: number;
}

export const ARTIST_UNIVERSE: UniverseArtist[] = [
  // ==========================================
  // 1. POST MALONE & LIL SKIES & SOUNDCLOUD/EMO RAP (SPECIAL PRIORITY)
  // ==========================================
  { name: 'Post Malone', targetCount: 40, genre: 'Hip-Hop/Rap' },
  { name: 'Lil Skies', targetCount: 25, genre: 'Hip-Hop/Rap' },
  { name: 'Juice WRLD', targetCount: 30, genre: 'Hip-Hop/Rap' },
  { name: 'XXXTentacion', targetCount: 25, genre: 'Hip-Hop/Rap' },
  { name: 'Lil Peep', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'Lil Uzi Vert', targetCount: 28, genre: 'Hip-Hop/Rap' },
  { name: 'Trippie Redd', targetCount: 22, genre: 'Hip-Hop/Rap' },
  { name: 'Ski Mask the Slump God', searchQuery: 'Ski Mask The Slump God', targetCount: 16, genre: 'Hip-Hop/Rap' },
  { name: 'Lil Pump', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Lil Mosey', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Lil Tecca', targetCount: 15, genre: 'Hip-Hop/Rap' },
  { name: 'Famous Dex', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'Fetty Wap', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'A Boogie wit da Hoodie', targetCount: 18, genre: 'Hip-Hop/Rap' },
  { name: 'YoungBoy Never Broke Again', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'YNW Melly', targetCount: 15, genre: 'Hip-Hop/Rap' },
  { name: 'Playboi Carti', targetCount: 22, genre: 'Hip-Hop/Rap' },
  { name: '$uicideboy$', targetCount: 16, genre: 'Hip-Hop/Rap' },
  { name: '6ix9ine', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Smokepurpp', targetCount: 8, genre: 'Hip-Hop/Rap' },
  { name: 'Iann Dior', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Trevor Daniel', targetCount: 6, genre: 'Pop' },
  { name: 'Yung Lean', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'Tay-K', targetCount: 5, genre: 'Hip-Hop/Rap' },
  { name: 'Rich Brian', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'Yung Pinch', targetCount: 8, genre: 'Hip-Hop/Rap' },

  // ==========================================
  // 2. POP / MAINSTREAM SUPERSTARS & ICONS (MASSIVE EXPANSION)
  // ==========================================
  { name: 'Taylor Swift', targetCount: 35, genre: 'Pop' },
  { name: 'Michael Jackson', targetCount: 35, genre: 'Pop' },
  { name: 'Madonna', targetCount: 30, genre: 'Pop' },
  { name: 'Britney Spears', targetCount: 30, genre: 'Pop' },
  { name: 'Beyoncé', searchQuery: 'Beyonce', targetCount: 32, genre: 'Pop' },
  { name: 'Rihanna', targetCount: 35, genre: 'Pop' },
  { name: 'Lady Gaga', targetCount: 30, genre: 'Pop' },
  { name: 'Katy Perry', targetCount: 30, genre: 'Pop' },
  { name: 'Ariana Grande', targetCount: 32, genre: 'Pop' },
  { name: 'Justin Bieber', targetCount: 32, genre: 'Pop' },
  { name: 'Ed Sheeran', targetCount: 30, genre: 'Pop' },
  { name: 'Bruno Mars', targetCount: 28, genre: 'Pop' },
  { name: 'Adele', targetCount: 25, genre: 'Pop' },
  { name: 'Dua Lipa', targetCount: 28, genre: 'Pop' },
  { name: 'Billie Eilish', targetCount: 28, genre: 'Pop' },
  { name: 'Olivia Rodrigo', targetCount: 22, genre: 'Pop' },
  { name: 'Sabrina Carpenter', targetCount: 20, genre: 'Pop' },
  { name: 'Doja Cat', targetCount: 25, genre: 'Pop' },
  { name: 'Chappell Roan', targetCount: 15, genre: 'Pop' },
  { name: 'Charli XCX', targetCount: 22, genre: 'Pop' },
  { name: 'Miley Cyrus', targetCount: 28, genre: 'Pop' },
  { name: 'Maroon 5', targetCount: 26, genre: 'Pop' },
  { name: 'Coldplay', targetCount: 28, genre: 'Rock' },
  { name: 'OneRepublic', targetCount: 20, genre: 'Pop' },
  { name: 'Sia', targetCount: 22, genre: 'Pop' },
  { name: 'P!nk', searchQuery: 'Pink', targetCount: 24, genre: 'Pop' },
  { name: 'Kelly Clarkson', targetCount: 20, genre: 'Pop' },
  { name: 'Avril Lavigne', targetCount: 22, genre: 'Pop' },
  { name: 'Christina Aguilera', targetCount: 22, genre: 'Pop' },
  { name: 'Backstreet Boys', targetCount: 22, genre: 'Pop' },
  { name: '*NSYNC', searchQuery: 'NSYNC', targetCount: 18, genre: 'Pop' },
  { name: 'Justin Timberlake', targetCount: 24, genre: 'Pop' },
  { name: 'Black Eyed Peas', targetCount: 25, genre: 'Pop' },
  { name: 'Fergie', targetCount: 12, genre: 'Pop' },
  { name: 'Kesha', targetCount: 20, genre: 'Pop' },
  { name: 'Pitbull', targetCount: 26, genre: 'Pop' },
  { name: 'Flo Rida', targetCount: 22, genre: 'Pop' },
  { name: 'Jason Derulo', targetCount: 22, genre: 'Pop' },
  { name: 'One Direction', targetCount: 24, genre: 'Pop' },
  { name: 'Harry Styles', targetCount: 20, genre: 'Pop' },
  { name: 'ZAYN', targetCount: 14, genre: 'Pop' },
  { name: 'Niall Horan', targetCount: 12, genre: 'Pop' },
  { name: 'Liam Payne', targetCount: 8, genre: 'Pop' },
  { name: 'Louis Tomlinson', targetCount: 8, genre: 'Pop' },
  { name: 'Shawn Mendes', targetCount: 20, genre: 'Pop' },
  { name: 'Camila Cabello', targetCount: 18, genre: 'Pop' },
  { name: 'Fifth Harmony', targetCount: 14, genre: 'Pop' },
  { name: 'Little Mix', targetCount: 18, genre: 'Pop' },
  { name: 'Selena Gomez', targetCount: 22, genre: 'Pop' },
  { name: 'Demi Lovato', targetCount: 20, genre: 'Pop' },
  { name: 'Ellie Goulding', targetCount: 18, genre: 'Pop' },
  { name: 'Halsey', targetCount: 20, genre: 'Pop' },
  { name: 'Charlie Puth', targetCount: 18, genre: 'Pop' },
  { name: 'Carly Rae Jepsen', targetCount: 16, genre: 'Pop' },
  { name: 'Meghan Trainor', targetCount: 16, genre: 'Pop' },
  { name: 'Zara Larsson', targetCount: 14, genre: 'Pop' },
  { name: 'Bebe Rexha', targetCount: 16, genre: 'Pop' },
  { name: 'Ava Max', targetCount: 16, genre: 'Pop' },
  { name: 'Tate McRae', targetCount: 16, genre: 'Pop' },
  { name: 'Gracie Abrams', targetCount: 14, genre: 'Pop' },
  { name: 'Benson Boone', targetCount: 12, genre: 'Pop' },
  { name: 'Teddy Swims', targetCount: 12, genre: 'Pop' },
  { name: 'Noah Kahan', targetCount: 15, genre: 'Country' },
  { name: 'Sam Smith', targetCount: 20, genre: 'Pop' },
  { name: 'Lewis Capaldi', targetCount: 14, genre: 'Pop' },
  { name: 'James Arthur', targetCount: 14, genre: 'Pop' },
  { name: 'George Ezra', targetCount: 12, genre: 'Pop' },
  { name: 'Tom Odell', targetCount: 10, genre: 'Pop' },
  { name: 'Conan Gray', targetCount: 14, genre: 'Pop' },
  { name: 'Troye Sivan', targetCount: 15, genre: 'Pop' },
  { name: 'Lauv', targetCount: 14, genre: 'Pop' },
  { name: 'Lorde', targetCount: 16, genre: 'Pop' },
  { name: 'Alessia Cara', targetCount: 12, genre: 'Pop' },
  { name: 'Rita Ora', targetCount: 16, genre: 'Pop' },
  { name: 'Jessie J', targetCount: 14, genre: 'Pop' },
  { name: 'Lizzo', targetCount: 15, genre: 'Pop' },
  { name: '5 Seconds of Summer', targetCount: 16, genre: 'Pop' },
  { name: 'The Wanted', targetCount: 10, genre: 'Pop' },
  { name: 'Jonas Brothers', targetCount: 20, genre: 'Pop' },
  { name: 'Nick Jonas', targetCount: 10, genre: 'Pop' },
  { name: 'DNCE', targetCount: 6, genre: 'Pop' },
  { name: 'Shakira', targetCount: 28, genre: 'Latin' },
  { name: 'Enrique Iglesias', targetCount: 24, genre: 'Latin' },
  { name: 'Ricky Martin', targetCount: 18, genre: 'Latin' },
  { name: 'Nelly Furtado', targetCount: 16, genre: 'Pop' },
  { name: 'Gwen Stefani', targetCount: 18, genre: 'Pop' },
  { name: 'No Doubt', targetCount: 16, genre: 'Rock' },
  { name: 'Hilary Duff', targetCount: 10, genre: 'Pop' },
  { name: 'JoJo', targetCount: 10, genre: 'Pop' },
  { name: 'Natasha Bedingfield', targetCount: 10, genre: 'Pop' },
  { name: 'Taio Cruz', targetCount: 10, genre: 'Pop' },
  { name: 'Jay Sean', targetCount: 10, genre: 'Pop' },
  { name: 'Owl City', targetCount: 10, genre: 'Pop' },
  { name: 'B.o.B', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Gym Class Heroes', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'Travie McCoy', targetCount: 6, genre: 'Pop' },
  { name: 'Clean Bandit', targetCount: 14, genre: 'Dance' },
  { name: 'Jess Glynne', targetCount: 12, genre: 'Pop' },
  { name: 'Anne-Marie', targetCount: 14, genre: 'Pop' },
  { name: 'Mabel', targetCount: 10, genre: 'Pop' },
  { name: 'Sigala', targetCount: 12, genre: 'Dance' },
  { name: 'Jax Jones', targetCount: 12, genre: 'Dance' },
  { name: 'Becky Hill', targetCount: 12, genre: 'Dance' },
  { name: 'Joel Corry', targetCount: 10, genre: 'Dance' },
  { name: 'Madison Beer', targetCount: 12, genre: 'Pop' },
  { name: 'Raye', targetCount: 14, genre: 'Pop' },
  { name: 'Marina', searchQuery: 'Marina and the Diamonds', targetCount: 14, genre: 'Pop' },
  { name: 'Melanie Martinez', targetCount: 15, genre: 'Pop' },
  { name: 'Oliver Tree', targetCount: 12, genre: 'Pop' },
  { name: 'JVKE', targetCount: 8, genre: 'Pop' },
  { name: 'Stephen Sanchez', targetCount: 8, genre: 'Pop' },
  { name: 'David Kushner', targetCount: 6, genre: 'Pop' },
  { name: 'Tommy Richman', targetCount: 6, genre: 'Hip-Hop/Rap' },
  { name: 'Shaboozey', targetCount: 8, genre: 'Country' },

  // Pre-2000s Pop Legends
  { name: 'Elton John', targetCount: 30, genre: 'Pop' },
  { name: 'Whitney Houston', targetCount: 28, genre: 'Pop' },
  { name: 'Mariah Carey', targetCount: 30, genre: 'Pop' },
  { name: 'Celine Dion', targetCount: 24, genre: 'Pop' },
  { name: 'Cher', targetCount: 22, genre: 'Pop' },
  { name: 'ABBA', targetCount: 25, genre: 'Pop' },
  { name: 'George Michael', targetCount: 22, genre: 'Pop' },
  { name: 'Wham!', searchQuery: 'Wham', targetCount: 10, genre: 'Pop' },
  { name: 'Phil Collins', targetCount: 22, genre: 'Pop' },
  { name: 'Genesis', targetCount: 16, genre: 'Rock' },
  { name: 'Prince', targetCount: 28, genre: 'Pop' },
  { name: 'Cyndi Lauper', targetCount: 14, genre: 'Pop' },
  { name: 'Janet Jackson', targetCount: 24, genre: 'Pop' },
  { name: 'Tina Turner', targetCount: 20, genre: 'Pop' },
  { name: 'Spice Girls', targetCount: 16, genre: 'Pop' },
  { name: 'Ace of Base', targetCount: 12, genre: 'Pop' },
  { name: 'Aqua', targetCount: 8, genre: 'Pop' },
  { name: 'Roxette', targetCount: 16, genre: 'Pop' },
  { name: 'A-ha', searchQuery: 'A-ha', targetCount: 12, genre: 'Pop' },
  { name: 'Duran Duran', targetCount: 18, genre: 'Pop' },
  { name: 'Tears for Fears', targetCount: 14, genre: 'Pop' },
  { name: 'Eurythmics', targetCount: 14, genre: 'Pop' },
  { name: 'Culture Club', targetCount: 10, genre: 'Pop' },
  { name: 'Rick Astley', targetCount: 8, genre: 'Pop' },
  { name: 'Kylie Minogue', targetCount: 22, genre: 'Pop' },
  { name: 'Paula Abdul', targetCount: 10, genre: 'Pop' },
  { name: 'Belinda Carlisle', targetCount: 10, genre: 'Pop' },
  { name: 'Laura Branigan', targetCount: 8, genre: 'Pop' },
  { name: 'Bonnie Tyler', targetCount: 10, genre: 'Pop' },
  { name: 'Kim Carnes', targetCount: 6, genre: 'Pop' },
  { name: 'Boney M.', searchQuery: 'Boney M', targetCount: 12, genre: 'Pop' },
  { name: 'Village People', targetCount: 8, genre: 'Pop' },
  { name: 'Rick Springfield', targetCount: 10, genre: 'Pop' },
  { name: 'Men at Work', targetCount: 8, genre: 'Pop' },
  { name: 'Dexys Midnight Runners', targetCount: 6, genre: 'Pop' },
  { name: 'The Human League', targetCount: 10, genre: 'Pop' },
  { name: 'Soft Cell', targetCount: 6, genre: 'Pop' },

  // ==========================================
  // 3. HIP-HOP / RAP (ALL ERAS - MASSIVE EXPANSION)
  // ==========================================
  { name: 'Drake', targetCount: 35, genre: 'Hip-Hop/Rap' },
  { name: 'Eminem', targetCount: 35, genre: 'Hip-Hop/Rap' },
  { name: 'Kanye West', targetCount: 35, genre: 'Hip-Hop/Rap' },
  { name: 'Kendrick Lamar', targetCount: 30, genre: 'Hip-Hop/Rap' },
  { name: 'Travis Scott', targetCount: 30, genre: 'Hip-Hop/Rap' },
  { name: 'J. Cole', targetCount: 28, genre: 'Hip-Hop/Rap' },
  { name: 'Future', targetCount: 32, genre: 'Hip-Hop/Rap' },
  { name: 'Lil Wayne', targetCount: 32, genre: 'Hip-Hop/Rap' },
  { name: 'Nicki Minaj', targetCount: 32, genre: 'Hip-Hop/Rap' },
  { name: '21 Savage', targetCount: 26, genre: 'Hip-Hop/Rap' },
  { name: 'Young Thug', targetCount: 26, genre: 'Hip-Hop/Rap' },
  { name: '50 Cent', targetCount: 26, genre: 'Hip-Hop/Rap' },
  { name: 'Jay-Z', targetCount: 28, genre: 'Hip-Hop/Rap' },
  { name: '2Pac', targetCount: 26, genre: 'Hip-Hop/Rap' },
  { name: 'The Notorious B.I.G.', targetCount: 22, genre: 'Hip-Hop/Rap' },
  { name: 'Snoop Dogg', targetCount: 28, genre: 'Hip-Hop/Rap' },
  { name: 'Dr. Dre', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'Nas', targetCount: 24, genre: 'Hip-Hop/Rap' },
  { name: 'Outkast', targetCount: 22, genre: 'Hip-Hop/Rap' },
  { name: 'T.I.', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'Ludacris', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'Nelly', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'DMX', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'Busta Rhymes', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'Ice Cube', targetCount: 18, genre: 'Hip-Hop/Rap' },
  { name: 'Cypress Hill', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'Wu-Tang Clan', targetCount: 16, genre: 'Hip-Hop/Rap' },
  { name: 'Mobb Deep', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Bone Thugs-N-Harmony', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'A Tribe Called Quest', targetCount: 16, genre: 'Hip-Hop/Rap' },
  { name: 'LL Cool J', targetCount: 16, genre: 'Hip-Hop/Rap' },
  { name: 'Warren G', targetCount: 8, genre: 'Hip-Hop/Rap' },
  { name: 'Coolio', targetCount: 8, genre: 'Hip-Hop/Rap' },
  { name: 'The Game', targetCount: 16, genre: 'Hip-Hop/Rap' },
  { name: 'Fat Joe', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'Ja Rule', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'Missy Elliott', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'Cardi B', targetCount: 18, genre: 'Hip-Hop/Rap' },
  { name: 'Megan Thee Stallion', targetCount: 18, genre: 'Hip-Hop/Rap' },
  { name: 'Lil Baby', targetCount: 25, genre: 'Hip-Hop/Rap' },
  { name: 'Gunna', targetCount: 22, genre: 'Hip-Hop/Rap' },
  { name: 'Roddy Ricch', targetCount: 16, genre: 'Hip-Hop/Rap' },
  { name: 'Polo G', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'Lil Tjay', targetCount: 18, genre: 'Hip-Hop/Rap' },
  { name: 'Don Toliver', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'Chief Keef', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'Kodak Black', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'Denzel Curry', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'A$AP Rocky', searchQuery: 'ASAP Rocky', targetCount: 24, genre: 'Hip-Hop/Rap' },
  { name: 'A$AP Ferg', searchQuery: 'ASAP Ferg', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Mac Miller', targetCount: 26, genre: 'Hip-Hop/Rap' },
  { name: 'Tyler, The Creator', targetCount: 24, genre: 'Hip-Hop/Rap' },
  { name: 'Childish Gambino', targetCount: 16, genre: 'Hip-Hop/Rap' },
  { name: 'Kid Cudi', targetCount: 22, genre: 'Hip-Hop/Rap' },
  { name: 'Big Sean', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'Wiz Khalifa', targetCount: 22, genre: 'Hip-Hop/Rap' },
  { name: 'French Montana', targetCount: 16, genre: 'Hip-Hop/Rap' },
  { name: 'Tyga', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'Rae Sremmurd', targetCount: 16, genre: 'Hip-Hop/Rap' },
  { name: 'Swae Lee', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'Lil Yachty', targetCount: 18, genre: 'Hip-Hop/Rap' },
  { name: 'DaBaby', targetCount: 18, genre: 'Hip-Hop/Rap' },
  { name: 'Jack Harlow', targetCount: 18, genre: 'Hip-Hop/Rap' },
  { name: 'Central Cee', targetCount: 18, genre: 'Hip-Hop/Rap' },
  { name: 'Dave', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'Stormzy', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'Skepta', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'Pop Smoke', targetCount: 22, genre: 'Hip-Hop/Rap' },
  { name: 'King Von', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'Lil Durk', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'NLE Choppa', targetCount: 16, genre: 'Hip-Hop/Rap' },
  { name: 'Logic', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'G-Eazy', targetCount: 18, genre: 'Hip-Hop/Rap' },
  { name: 'NF', targetCount: 18, genre: 'Hip-Hop/Rap' },
  { name: 'Migos', targetCount: 22, genre: 'Hip-Hop/Rap' },
  { name: 'Quavo', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'Offset', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'Takeoff', targetCount: 8, genre: 'Hip-Hop/Rap' },
  { name: 'Ice Spice', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Latto', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Glorilla', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'Sexyy Red', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'Coi Leray', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'The Kid LAROI', targetCount: 18, genre: 'Hip-Hop/Rap' },
  { name: 'Joyner Lucas', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Schoolboy Q', targetCount: 15, genre: 'Hip-Hop/Rap' },
  { name: 'Vince Staples', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Pusha T', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'Rick Ross', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'Meek Mill', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'Waka Flocka Flame', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'Gucci Mane', targetCount: 22, genre: 'Hip-Hop/Rap' },
  { name: 'Soulja Boy', targetCount: 12, genre: 'Hip-Hop/Rap' },
  { name: 'Bow Wow', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'Chingy', targetCount: 8, genre: 'Hip-Hop/Rap' },
  { name: 'Chamillionaire', targetCount: 8, genre: 'Hip-Hop/Rap' },
  { name: 'Mike Jones', targetCount: 6, genre: 'Hip-Hop/Rap' },
  { name: 'Paul Wall', targetCount: 6, genre: 'Hip-Hop/Rap' },
  { name: 'Lil Jon', targetCount: 14, genre: 'Hip-Hop/Rap' },
  { name: 'Ying Yang Twins', targetCount: 10, genre: 'Hip-Hop/Rap' },
  { name: 'Petey Pablo', targetCount: 6, genre: 'Hip-Hop/Rap' },
  { name: 'J-Kwon', targetCount: 4, genre: 'Hip-Hop/Rap' },
  { name: 'Terror Squad', targetCount: 6, genre: 'Hip-Hop/Rap' },

  // ==========================================
  // 4. R&B / SOUL / FUNK
  // ==========================================
  { name: 'The Weeknd', targetCount: 35, genre: 'R&B/Soul' },
  { name: 'Usher', targetCount: 30, genre: 'R&B/Soul' },
  { name: 'Chris Brown', targetCount: 30, genre: 'R&B/Soul' },
  { name: 'Alicia Keys', targetCount: 26, genre: 'R&B/Soul' },
  { name: 'Frank Ocean', targetCount: 24, genre: 'R&B/Soul' },
  { name: 'SZA', targetCount: 28, genre: 'R&B/Soul' },
  { name: 'Ne-Yo', targetCount: 24, genre: 'R&B/Soul' },
  { name: 'John Legend', targetCount: 22, genre: 'R&B/Soul' },
  { name: 'Stevie Wonder', targetCount: 28, genre: 'R&B/Soul' },
  { name: 'Marvin Gaye', targetCount: 24, genre: 'R&B/Soul' },
  { name: 'Aretha Franklin', targetCount: 22, genre: 'R&B/Soul' },
  { name: 'Earth, Wind & Fire', searchQuery: 'Earth Wind and Fire', targetCount: 24, genre: 'R&B/Soul' },
  { name: 'James Brown', targetCount: 22, genre: 'R&B/Soul' },
  { name: 'Otis Redding', targetCount: 16, genre: 'R&B/Soul' },
  { name: 'Al Green', targetCount: 16, genre: 'R&B/Soul' },
  { name: 'Bill Withers', targetCount: 14, genre: 'R&B/Soul' },
  { name: 'Kool & The Gang', searchQuery: 'Kool and The Gang', targetCount: 18, genre: 'R&B/Soul' },
  { name: 'Donna Summer', targetCount: 20, genre: 'R&B/Soul' },
  { name: 'Bee Gees', targetCount: 24, genre: 'Pop' },
  { name: 'CHIC', targetCount: 14, genre: 'R&B/Soul' },
  { name: 'Sister Sledge', targetCount: 10, genre: 'R&B/Soul' },
  { name: 'Rick James', targetCount: 12, genre: 'R&B/Soul' },
  { name: 'Lionel Richie', targetCount: 22, genre: 'R&B/Soul' },
  { name: 'Commodores', targetCount: 14, genre: 'R&B/Soul' },
  { name: 'Sade', targetCount: 20, genre: 'R&B/Soul' },
  { name: 'Chaka Khan', targetCount: 16, genre: 'R&B/Soul' },
  { name: 'Luther Vandross', targetCount: 18, genre: 'R&B/Soul' },
  { name: 'Barry White', targetCount: 16, genre: 'R&B/Soul' },
  { name: 'The Temptations', targetCount: 20, genre: 'R&B/Soul' },
  { name: 'The Supremes', targetCount: 20, genre: 'R&B/Soul' },
  { name: 'The Isley Brothers', targetCount: 16, genre: 'R&B/Soul' },
  { name: 'Aaliyah', targetCount: 20, genre: 'R&B/Soul' },
  { name: 'TLC', targetCount: 20, genre: 'R&B/Soul' },
  { name: 'Destiny\'s Child', searchQuery: 'Destinys Child', targetCount: 22, genre: 'R&B/Soul' },
  { name: 'Boyz II Men', targetCount: 20, genre: 'R&B/Soul' },
  { name: 'Mary J. Blige', targetCount: 22, genre: 'R&B/Soul' },
  { name: 'Brandy', targetCount: 16, genre: 'R&B/Soul' },
  { name: 'Monica', targetCount: 14, genre: 'R&B/Soul' },
  { name: 'Toni Braxton', targetCount: 18, genre: 'R&B/Soul' },
  { name: 'Ginuwine', targetCount: 12, genre: 'R&B/Soul' },
  { name: 'Craig David', targetCount: 16, genre: 'R&B/Soul' },
  { name: 'Mario', targetCount: 12, genre: 'R&B/Soul' },
  { name: 'Ciara', targetCount: 18, genre: 'R&B/Soul' },
  { name: 'Trey Songz', targetCount: 18, genre: 'R&B/Soul' },
  { name: 'Keyshia Cole', targetCount: 12, genre: 'R&B/Soul' },
  { name: 'Ashanti', targetCount: 16, genre: 'R&B/Soul' },
  { name: 'Amy Winehouse', targetCount: 20, genre: 'R&B/Soul' },
  { name: 'Erykah Badu', targetCount: 16, genre: 'R&B/Soul' },
  { name: 'Lauryn Hill', targetCount: 14, genre: 'R&B/Soul' },
  { name: 'Bryson Tiller', targetCount: 18, genre: 'R&B/Soul' },
  { name: 'PARTYNEXTDOOR', targetCount: 18, genre: 'R&B/Soul' },
  { name: 'Jhené Aiko', searchQuery: 'Jhene Aiko', targetCount: 18, genre: 'R&B/Soul' },
  { name: 'Kehlani', targetCount: 18, genre: 'R&B/Soul' },
  { name: 'Summer Walker', targetCount: 18, genre: 'R&B/Soul' },
  { name: 'Brent Faiyaz', targetCount: 18, genre: 'R&B/Soul' },
  { name: 'Giveon', targetCount: 15, genre: 'R&B/Soul' },
  { name: 'Daniel Caesar', targetCount: 16, genre: 'R&B/Soul' },
  { name: 'H.E.R.', searchQuery: 'H.E.R.', targetCount: 18, genre: 'R&B/Soul' },
  { name: 'Khalid', targetCount: 24, genre: 'R&B/Soul' },
  { name: 'Miguel', targetCount: 16, genre: 'R&B/Soul' },
  { name: 'Tory Lanez', targetCount: 18, genre: 'Hip-Hop/Rap' },
  { name: '6LACK', targetCount: 15, genre: 'R&B/Soul' },
  { name: 'Kali Uchis', targetCount: 18, genre: 'R&B/Soul' },
  { name: 'Jorja Smith', targetCount: 14, genre: 'R&B/Soul' },
  { name: 'Ella Mai', targetCount: 14, genre: 'R&B/Soul' },
  { name: 'T-Pain', targetCount: 24, genre: 'R&B/Soul' },
  { name: 'Sean Kingston', targetCount: 12, genre: 'Pop' },
  { name: 'Sean Paul', targetCount: 22, genre: 'Pop' },
  { name: 'Shaggy', targetCount: 14, genre: 'Pop' },
  { name: 'Musiq Soulchild', targetCount: 12, genre: 'R&B/Soul' },
  { name: 'Anthony Hamilton', targetCount: 10, genre: 'R&B/Soul' },
  { name: 'D\'Angelo', searchQuery: 'DAngelo', targetCount: 12, genre: 'R&B/Soul' },
  { name: 'Maxwell', targetCount: 12, genre: 'R&B/Soul' },
  { name: 'Robin Thicke', targetCount: 12, genre: 'R&B/Soul' },
  { name: 'Jeremih', targetCount: 16, genre: 'R&B/Soul' },
  { name: 'August Alsina', targetCount: 12, genre: 'R&B/Soul' },
  { name: 'Ty Dolla $ign', searchQuery: 'Ty Dolla Sign', targetCount: 20, genre: 'Hip-Hop/Rap' },
  { name: 'Keri Hilson', targetCount: 10, genre: 'Pop' },
  { name: 'Mýa', searchQuery: 'Mya', targetCount: 10, genre: 'R&B/Soul' },
  { name: 'Amerie', targetCount: 8, genre: 'R&B/Soul' },
  { name: '112', targetCount: 10, genre: 'R&B/Soul' },
  { name: 'Jagged Edge', targetCount: 12, genre: 'R&B/Soul' },
  { name: 'Dru Hill', targetCount: 10, genre: 'R&B/Soul' },
  { name: 'Sisqo', targetCount: 6, genre: 'R&B/Soul' },
  { name: 'Blackstreet', targetCount: 8, genre: 'R&B/Soul' },
  { name: 'Montell Jordan', targetCount: 6, genre: 'R&B/Soul' },

  // ==========================================
  // 5. DANCE / ELECTRONIC / EDM / HOUSE
  // ==========================================
  { name: 'Calvin Harris', targetCount: 30, genre: 'Dance' },
  { name: 'David Guetta', targetCount: 30, genre: 'Dance' },
  { name: 'Avicii', targetCount: 28, genre: 'Dance' },
  { name: 'Daft Punk', targetCount: 26, genre: 'Dance' },
  { name: 'The Chainsmokers', targetCount: 24, genre: 'Dance' },
  { name: 'Marshmello', targetCount: 24, genre: 'Dance' },
  { name: 'Martin Garrix', targetCount: 24, genre: 'Dance' },
  { name: 'Kygo', targetCount: 24, genre: 'Dance' },
  { name: 'Tiësto', searchQuery: 'Tiesto', targetCount: 26, genre: 'Dance' },
  { name: 'Skrillex', targetCount: 24, genre: 'Dance' },
  { name: 'Deadmau5', targetCount: 22, genre: 'Dance' },
  { name: 'Zedd', targetCount: 22, genre: 'Dance' },
  { name: 'Swedish House Mafia', targetCount: 20, genre: 'Dance' },
  { name: 'Major Lazer', targetCount: 20, genre: 'Dance' },
  { name: 'DJ Snake', targetCount: 20, genre: 'Dance' },
  { name: 'Alan Walker', targetCount: 20, genre: 'Dance' },
  { name: 'Alesso', targetCount: 18, genre: 'Dance' },
  { name: 'Afrojack', targetCount: 18, genre: 'Dance' },
  { name: 'Steve Aoki', targetCount: 18, genre: 'Dance' },
  { name: 'Galantis', targetCount: 16, genre: 'Dance' },
  { name: 'Robin Schulz', targetCount: 18, genre: 'Dance' },
  { name: 'Lost Frequencies', targetCount: 16, genre: 'Dance' },
  { name: 'Jonas Blue', targetCount: 16, genre: 'Dance' },
  { name: 'Disclosure', targetCount: 20, genre: 'Dance' },
  { name: 'Flume', targetCount: 18, genre: 'Dance' },
  { name: 'ODESZA', targetCount: 16, genre: 'Dance' },
  { name: 'RÜFÜS DU SOL', searchQuery: 'Rufus Du Sol', targetCount: 16, genre: 'Dance' },
  { name: 'Fred again..', searchQuery: 'Fred again', targetCount: 20, genre: 'Dance' },
  { name: 'Fisher', targetCount: 12, genre: 'Dance' },
  { name: 'Peggy Gou', targetCount: 10, genre: 'Dance' },
  { name: 'Dom Dolla', targetCount: 12, genre: 'Dance' },
  { name: 'John Summit', targetCount: 14, genre: 'Dance' },
  { name: 'Meduza', targetCount: 14, genre: 'Dance' },
  { name: 'Oliver Heldens', targetCount: 16, genre: 'Dance' },
  { name: 'Hardwell', targetCount: 16, genre: 'Dance' },
  { name: 'Armin van Buuren', targetCount: 18, genre: 'Dance' },
  { name: 'The Prodigy', targetCount: 20, genre: 'Dance' },
  { name: 'Fatboy Slim', targetCount: 18, genre: 'Dance' },
  { name: 'The Chemical Brothers', targetCount: 18, genre: 'Dance' },
  { name: 'Faithless', targetCount: 12, genre: 'Dance' },
  { name: 'Moby', targetCount: 18, genre: 'Dance' },
  { name: 'Underworld', targetCount: 12, genre: 'Dance' },
  { name: 'Pendulum', targetCount: 14, genre: 'Dance' },
  { name: 'Chase & Status', searchQuery: 'Chase and Status', targetCount: 14, genre: 'Dance' },
  { name: 'Sub Focus', targetCount: 12, genre: 'Dance' },
  { name: 'Netsky', targetCount: 10, genre: 'Dance' },
  { name: 'Kaskade', targetCount: 16, genre: 'Dance' },
  { name: 'Above & Beyond', searchQuery: 'Above and Beyond', targetCount: 14, genre: 'Dance' },
  { name: 'Dash Berlin', targetCount: 12, genre: 'Dance' },
  { name: 'Nicky Romero', targetCount: 12, genre: 'Dance' },
  { name: 'DVBBS', targetCount: 8, genre: 'Dance' },
  { name: 'Deorro', targetCount: 10, genre: 'Dance' },
  { name: 'Showtek', targetCount: 10, genre: 'Dance' },
  { name: 'Dimitri Vegas & Like Mike', targetCount: 12, genre: 'Dance' },
  { name: 'W&W', searchQuery: 'W and W', targetCount: 10, genre: 'Dance' },
  { name: 'KSHMR', targetCount: 12, genre: 'Dance' },
  { name: 'Gorgon City', targetCount: 14, genre: 'Dance' },
  { name: 'Duke Dumont', targetCount: 12, genre: 'Dance' },
  { name: 'Route 94', targetCount: 6, genre: 'Dance' },
  { name: 'Secondcity', targetCount: 4, genre: 'Dance' },
  { name: 'MK', searchQuery: 'MK', targetCount: 12, genre: 'Dance' },
  { name: 'CamelPhat', targetCount: 12, genre: 'Dance' },
  { name: 'Sonny Fodera', targetCount: 10, genre: 'Dance' },
  { name: 'Solardo', targetCount: 8, genre: 'Dance' },
  { name: 'Patrick Topping', targetCount: 8, genre: 'Dance' },
  { name: 'Chris Lake', targetCount: 14, genre: 'Dance' },
  { name: 'Bicep', targetCount: 10, genre: 'Dance' },
  { name: 'Four Tet', targetCount: 12, genre: 'Dance' },
  { name: 'Bonobo', targetCount: 14, genre: 'Dance' },
  { name: 'Caribou', targetCount: 10, genre: 'Dance' },
  { name: 'Kaytranada', targetCount: 16, genre: 'Dance' },
  { name: 'Channel Tres', targetCount: 10, genre: 'Dance' },
  { name: 'Porter Robinson', targetCount: 14, genre: 'Dance' },
  { name: 'Madeon', targetCount: 12, genre: 'Dance' },
  { name: 'Illenium', targetCount: 16, genre: 'Dance' },
  { name: 'San Holo', targetCount: 12, genre: 'Dance' },
  { name: 'Gryffin', targetCount: 14, genre: 'Dance' },
  { name: 'SLANDER', targetCount: 12, genre: 'Dance' },
  { name: 'Excision', targetCount: 12, genre: 'Dance' },
  { name: 'Flux Pavilion', targetCount: 10, genre: 'Dance' },
  { name: 'Nero', targetCount: 10, genre: 'Dance' },
  { name: 'Knife Party', targetCount: 10, genre: 'Dance' },
  { name: 'Zomboy', targetCount: 8, genre: 'Dance' },
  { name: 'Cascada', targetCount: 14, genre: 'Dance' },
  { name: 'Basshunter', targetCount: 10, genre: 'Dance' },
  { name: 'Darude', targetCount: 6, genre: 'Dance' },
  { name: 'Alice Deejay', targetCount: 6, genre: 'Dance' },
  { name: 'ATB', targetCount: 12, genre: 'Dance' },
  { name: 'Benny Benassi', targetCount: 10, genre: 'Dance' },
  { name: 'Eric Prydz', targetCount: 14, genre: 'Dance' },
  { name: 'Fedde Le Grand', targetCount: 10, genre: 'Dance' },
  { name: 'Bob Sinclar', targetCount: 12, genre: 'Dance' },
  { name: 'Junior Jack', targetCount: 8, genre: 'Dance' },
  { name: 'Armand Van Helden', targetCount: 12, genre: 'Dance' },
  { name: 'Groove Armada', targetCount: 12, genre: 'Dance' },
  { name: 'Basement Jaxx', targetCount: 12, genre: 'Dance' },
  { name: 'Paul van Dyk', targetCount: 12, genre: 'Dance' },
  { name: 'Robert Miles', targetCount: 6, genre: 'Dance' },
  { name: 'Gigi D\'Agostino', searchQuery: 'Gigi DAgostino', targetCount: 10, genre: 'Dance' },
  { name: 'Eiffel 65', targetCount: 8, genre: 'Dance' },
  { name: 'Vengaboys', targetCount: 10, genre: 'Dance' },
  { name: '2 Unlimited', targetCount: 8, genre: 'Dance' },
  { name: 'Snap!', searchQuery: 'Snap', targetCount: 8, genre: 'Dance' },
  { name: 'Corona', targetCount: 6, genre: 'Dance' },
  { name: 'La Bouche', targetCount: 6, genre: 'Dance' },
  { name: 'Real McCoy', targetCount: 6, genre: 'Dance' },
  { name: 'Culture Beat', targetCount: 6, genre: 'Dance' },
  { name: 'Haddaway', targetCount: 6, genre: 'Dance' },
  { name: 'Scatman John', targetCount: 4, genre: 'Dance' },

  // ==========================================
  // 6. LATIN / REGGAETON / REGIONAL MEXICAN / TRAP LATINO
  // ==========================================
  { name: 'Bad Bunny', targetCount: 35, genre: 'Latin' },
  { name: 'Daddy Yankee', targetCount: 30, genre: 'Latin' },
  { name: 'J Balvin', targetCount: 28, genre: 'Latin' },
  { name: 'Ozuna', targetCount: 28, genre: 'Latin' },
  { name: 'Karol G', targetCount: 28, genre: 'Latin' },
  { name: 'Rauw Alejandro', targetCount: 26, genre: 'Latin' },
  { name: 'Anuel AA', targetCount: 26, genre: 'Latin' },
  { name: 'Feid', targetCount: 26, genre: 'Latin' },
  { name: 'Myke Towers', targetCount: 24, genre: 'Latin' },
  { name: 'Maluma', targetCount: 26, genre: 'Latin' },
  { name: 'Nicky Jam', targetCount: 24, genre: 'Latin' },
  { name: 'Farruko', targetCount: 24, genre: 'Latin' },
  { name: 'Don Omar', targetCount: 24, genre: 'Latin' },
  { name: 'Wisin & Yandel', searchQuery: 'Wisin y Yandel', targetCount: 24, genre: 'Latin' },
  { name: 'Wisin', targetCount: 14, genre: 'Latin' },
  { name: 'Yandel', targetCount: 14, genre: 'Latin' },
  { name: 'Zion & Lennox', searchQuery: 'Zion y Lennox', targetCount: 16, genre: 'Latin' },
  { name: 'Tego Calderón', searchQuery: 'Tego Calderon', targetCount: 14, genre: 'Latin' },
  { name: 'Calle 13', targetCount: 16, genre: 'Latin' },
  { name: 'Residente', targetCount: 12, genre: 'Latin' },
  { name: 'Plan B', targetCount: 14, genre: 'Latin' },
  { name: 'Arcángel', searchQuery: 'Arcangel', targetCount: 20, genre: 'Latin' },
  { name: 'De La Ghetto', targetCount: 14, genre: 'Latin' },
  { name: 'J Alvarez', targetCount: 12, genre: 'Latin' },
  { name: 'Alexis & Fido', searchQuery: 'Alexis y Fido', targetCount: 12, genre: 'Latin' },
  { name: 'Jowell & Randy', searchQuery: 'Jowell y Randy', targetCount: 14, genre: 'Latin' },
  { name: 'Ivy Queen', targetCount: 12, genre: 'Latin' },
  { name: 'Quevedo', targetCount: 18, genre: 'Latin' },
  { name: 'Rosalía', searchQuery: 'Rosalia', targetCount: 24, genre: 'Latin' },
  { name: 'Sech', targetCount: 16, genre: 'Latin' },
  { name: 'Jhayco', searchQuery: 'Jhay Cortez', targetCount: 18, genre: 'Latin' },
  { name: 'Mora', targetCount: 18, genre: 'Latin' },
  { name: 'Manuel Turizo', targetCount: 16, genre: 'Latin' },
  { name: 'Sebastián Yatra', searchQuery: 'Sebastian Yatra', targetCount: 18, genre: 'Latin' },
  { name: 'Camilo', targetCount: 16, genre: 'Latin' },
  { name: 'Luis Fonsi', targetCount: 20, genre: 'Latin' },
  { name: 'Romeo Santos', targetCount: 24, genre: 'Latin' },
  { name: 'Aventura', targetCount: 20, genre: 'Latin' },
  { name: 'Prince Royce', targetCount: 18, genre: 'Latin' },
  { name: 'Natti Natasha', targetCount: 16, genre: 'Latin' },
  { name: 'Becky G', targetCount: 18, genre: 'Latin' },
  { name: 'Anitta', targetCount: 18, genre: 'Latin' },
  { name: 'Duki', targetCount: 18, genre: 'Latin' },
  { name: 'Bizarrap', targetCount: 22, genre: 'Latin' },
  { name: 'Maria Becerra', targetCount: 16, genre: 'Latin' },
  { name: 'Nicki Nicole', targetCount: 14, genre: 'Latin' },
  { name: 'Young Miko', targetCount: 14, genre: 'Latin' },
  { name: 'Tiago PZK', targetCount: 14, genre: 'Latin' },
  { name: 'Emilia', targetCount: 14, genre: 'Latin' },
  { name: 'Trueno', targetCount: 14, genre: 'Latin' },
  { name: 'Khea', targetCount: 12, genre: 'Latin' },
  { name: 'Cazzu', targetCount: 12, genre: 'Latin' },
  { name: 'Peso Pluma', targetCount: 24, genre: 'Latin' },
  { name: 'Natanael Cano', targetCount: 22, genre: 'Latin' },
  { name: 'Fuerza Regida', targetCount: 22, genre: 'Latin' },
  { name: 'Junior H', targetCount: 22, genre: 'Latin' },
  { name: 'Grupo Frontera', targetCount: 18, genre: 'Latin' },
  { name: 'Eslabon Armado', targetCount: 16, genre: 'Latin' },
  { name: 'Carin Leon', targetCount: 20, genre: 'Latin' },
  { name: 'Christian Nodal', targetCount: 20, genre: 'Latin' },
  { name: 'Grupo Firme', targetCount: 18, genre: 'Latin' },
  { name: 'Banda MS', targetCount: 16, genre: 'Latin' },
  { name: 'Calibre 50', targetCount: 14, genre: 'Latin' },
  { name: 'Los Ángeles Azules', searchQuery: 'Los Angeles Azules', targetCount: 14, genre: 'Latin' },
  { name: 'Selena', targetCount: 20, genre: 'Latin' },
  { name: 'Juanes', targetCount: 18, genre: 'Latin' },
  { name: 'Maná', searchQuery: 'Mana', targetCount: 20, genre: 'Latin' },
  { name: 'Marc Anthony', targetCount: 20, genre: 'Latin' },
  { name: 'Carlos Vives', targetCount: 16, genre: 'Latin' },
  { name: 'Chayanne', targetCount: 16, genre: 'Latin' },
  { name: 'Alejandro Sanz', targetCount: 18, genre: 'Latin' },
  { name: 'Luis Miguel', targetCount: 22, genre: 'Latin' },
  { name: 'Gente de Zona', targetCount: 12, genre: 'Latin' },
  { name: 'CNCO', targetCount: 12, genre: 'Latin' },
  { name: 'Reik', targetCount: 16, genre: 'Latin' },
  { name: 'Morat', targetCount: 16, genre: 'Latin' },
  { name: 'Jesse & Joy', searchQuery: 'Jesse y Joy', targetCount: 14, genre: 'Latin' },
  { name: 'Ha*Ash', searchQuery: 'Ha-Ash', targetCount: 14, genre: 'Latin' },
  { name: 'Paulina Rubio', targetCount: 12, genre: 'Latin' },
  { name: 'Thalía', searchQuery: 'Thalia', targetCount: 14, genre: 'Latin' },
  { name: 'Gloria Estefan', targetCount: 16, genre: 'Latin' },

  // ==========================================
  // 7. ROCK / ALTERNATIVE / INDIE / PUNK
  // ==========================================
  { name: 'Queen', targetCount: 32, genre: 'Rock' },
  { name: 'The Beatles', targetCount: 32, genre: 'Rock' },
  { name: 'The Rolling Stones', targetCount: 28, genre: 'Rock' },
  { name: 'AC/DC', targetCount: 28, genre: 'Rock' },
  { name: 'Pink Floyd', targetCount: 25, genre: 'Rock' },
  { name: 'Led Zeppelin', targetCount: 26, genre: 'Rock' },
  { name: 'Fleetwood Mac', targetCount: 26, genre: 'Rock' },
  { name: 'David Bowie', targetCount: 28, genre: 'Rock' },
  { name: 'Guns N\' Roses', searchQuery: 'Guns N Roses', targetCount: 26, genre: 'Rock' },
  { name: 'Aerosmith', targetCount: 24, genre: 'Rock' },
  { name: 'Nirvana', targetCount: 26, genre: 'Rock' },
  { name: 'Linkin Park', targetCount: 30, genre: 'Rock' },
  { name: 'Red Hot Chili Peppers', targetCount: 30, genre: 'Rock' },
  { name: 'Green Day', targetCount: 28, genre: 'Rock' },
  { name: 'Foo Fighters', targetCount: 26, genre: 'Rock' },
  { name: 'Blink-182', targetCount: 25, genre: 'Rock' },
  { name: 'Arctic Monkeys', targetCount: 28, genre: 'Rock' },
  { name: 'The Killers', targetCount: 25, genre: 'Rock' },
  { name: 'Muse', targetCount: 25, genre: 'Rock' },
  { name: 'Radiohead', targetCount: 26, genre: 'Rock' },
  { name: 'Oasis', targetCount: 25, genre: 'Rock' },
  { name: 'U2', targetCount: 28, genre: 'Rock' },
  { name: 'Bon Jovi', targetCount: 25, genre: 'Rock' },
  { name: 'The Police', targetCount: 20, genre: 'Rock' },
  { name: 'Sting', targetCount: 16, genre: 'Rock' },
  { name: 'Bruce Springsteen', targetCount: 26, genre: 'Rock' },
  { name: 'Tom Petty', targetCount: 20, genre: 'Rock' },
  { name: 'Creedence Clearwater Revival', targetCount: 22, genre: 'Rock' },
  { name: 'Van Halen', targetCount: 22, genre: 'Rock' },
  { name: 'Def Leppard', targetCount: 20, genre: 'Rock' },
  { name: 'The Who', targetCount: 18, genre: 'Rock' },
  { name: 'The Doors', targetCount: 18, genre: 'Rock' },
  { name: 'Eagles', targetCount: 20, genre: 'Rock' },
  { name: 'Boston', targetCount: 12, genre: 'Rock' },
  { name: 'Deep Purple', targetCount: 16, genre: 'Rock' },
  { name: 'KISS', targetCount: 20, genre: 'Rock' },
  { name: 'Journey', targetCount: 18, genre: 'Rock' },
  { name: 'Toto', targetCount: 14, genre: 'Rock' },
  { name: 'Dire Straits', targetCount: 18, genre: 'Rock' },
  { name: 'Mark Knopfler', targetCount: 10, genre: 'Rock' },
  { name: 'Eric Clapton', targetCount: 20, genre: 'Rock' },
  { name: 'Cream', targetCount: 10, genre: 'Rock' },
  { name: 'Jimi Hendrix', targetCount: 20, genre: 'Rock' },
  { name: 'Bob Dylan', targetCount: 24, genre: 'Rock' },
  { name: 'Neil Young', targetCount: 18, genre: 'Rock' },
  { name: 'The Cure', targetCount: 24, genre: 'Rock' },
  { name: 'Depeche Mode', targetCount: 24, genre: 'Rock' },
  { name: 'New Order', targetCount: 16, genre: 'Rock' },
  { name: 'The Smiths', targetCount: 18, genre: 'Rock' },
  { name: 'Joy Division', targetCount: 10, genre: 'Rock' },
  { name: 'The Clash', targetCount: 16, genre: 'Rock' },
  { name: 'Ramones', targetCount: 16, genre: 'Rock' },
  { name: 'Sex Pistols', targetCount: 8, genre: 'Rock' },
  { name: 'Blondie', targetCount: 16, genre: 'Rock' },
  { name: 'Pearl Jam', targetCount: 24, genre: 'Rock' },
  { name: 'Soundgarden', targetCount: 16, genre: 'Rock' },
  { name: 'Alice in Chains', targetCount: 18, genre: 'Rock' },
  { name: 'Stone Temple Pilots', targetCount: 16, genre: 'Rock' },
  { name: 'Smashing Pumpkins', targetCount: 22, genre: 'Rock' },
  { name: 'Weezer', targetCount: 24, genre: 'Rock' },
  { name: 'The Offspring', targetCount: 22, genre: 'Rock' },
  { name: 'Blur', targetCount: 18, genre: 'Rock' },
  { name: 'Gorillaz', targetCount: 24, genre: 'Rock' },
  { name: 'The Cranberries', targetCount: 16, genre: 'Rock' },
  { name: 'R.E.M.', targetCount: 22, genre: 'Rock' },
  { name: 'Sum 41', targetCount: 18, genre: 'Rock' },
  { name: 'Good Charlotte', targetCount: 14, genre: 'Rock' },
  { name: 'Simple Plan', targetCount: 14, genre: 'Rock' },
  { name: 'Audioslave', targetCount: 14, genre: 'Rock' },
  { name: 'Rage Against the Machine', targetCount: 20, genre: 'Rock' },
  { name: 'Sublime', targetCount: 16, genre: 'Rock' },
  { name: 'Third Eye Blind', targetCount: 14, genre: 'Rock' },
  { name: 'Matchbox Twenty', targetCount: 16, genre: 'Rock' },
  { name: 'Goo Goo Dolls', targetCount: 16, genre: 'Rock' },
  { name: 'The Strokes', targetCount: 22, genre: 'Rock' },
  { name: 'The White Stripes', targetCount: 20, genre: 'Rock' },
  { name: 'Jack White', targetCount: 12, genre: 'Rock' },
  { name: 'Franz Ferdinand', targetCount: 14, genre: 'Rock' },
  { name: 'Kings of Leon', targetCount: 20, genre: 'Rock' },
  { name: 'Paramore', targetCount: 25, genre: 'Rock' },
  { name: 'Fall Out Boy', targetCount: 25, genre: 'Rock' },
  { name: 'My Chemical Romance', targetCount: 22, genre: 'Rock' },
  { name: 'Panic! At The Disco', searchQuery: 'Panic At The Disco', targetCount: 24, genre: 'Rock' },
  { name: 'Evanescence', targetCount: 20, genre: 'Rock' },
  { name: 'Nickelback', targetCount: 22, genre: 'Rock' },
  { name: 'Three Days Grace', targetCount: 20, genre: 'Rock' },
  { name: 'Breaking Benjamin', targetCount: 18, genre: 'Rock' },
  { name: 'Papa Roach', targetCount: 18, genre: 'Rock' },
  { name: 'Limp Bizkit', targetCount: 20, genre: 'Rock' },
  { name: 'Rise Against', targetCount: 18, genre: 'Rock' },
  { name: 'Jimmy Eat World', targetCount: 14, genre: 'Rock' },
  { name: 'Yellowcard', targetCount: 12, genre: 'Rock' },
  { name: 'All Time Low', targetCount: 16, genre: 'Rock' },
  { name: 'The All-American Rejects', targetCount: 14, genre: 'Rock' },
  { name: 'Snow Patrol', targetCount: 16, genre: 'Rock' },
  { name: 'Keane', targetCount: 16, genre: 'Rock' },
  { name: 'The Kooks', targetCount: 12, genre: 'Rock' },
  { name: 'Kasabian', targetCount: 14, genre: 'Rock' },
  { name: 'Stereophonics', targetCount: 14, genre: 'Rock' },
  { name: 'Manic Street Preachers', targetCount: 14, genre: 'Rock' },
  { name: 'Travis', targetCount: 12, genre: 'Rock' },
  { name: 'The Verve', targetCount: 10, genre: 'Rock' },
  { name: 'Richard Ashcroft', targetCount: 8, genre: 'Rock' },
  { name: 'Pulp', targetCount: 12, genre: 'Rock' },
  { name: 'Supergrass', targetCount: 10, genre: 'Rock' },
  { name: 'The Stone Roses', targetCount: 10, genre: 'Rock' },
  { name: 'Primal Scream', targetCount: 12, genre: 'Rock' },
  { name: 'Twenty One Pilots', targetCount: 28, genre: 'Rock' },
  { name: 'Imagine Dragons', targetCount: 28, genre: 'Rock' },
  { name: 'The 1975', targetCount: 24, genre: 'Rock' },
  { name: 'Tame Impala', targetCount: 22, genre: 'Alternative' },
  { name: 'The Black Keys', targetCount: 20, genre: 'Rock' },
  { name: 'Cage The Elephant', targetCount: 18, genre: 'Rock' },
  { name: 'Glass Animals', targetCount: 16, genre: 'Alternative' },
  { name: 'Florence + The Machine', searchQuery: 'Florence and The Machine', targetCount: 20, genre: 'Alternative' },
  { name: 'Mumford & Sons', searchQuery: 'Mumford and Sons', targetCount: 20, genre: 'Rock' },
  { name: 'The Lumineers', targetCount: 16, genre: 'Rock' },
  { name: 'Vance Joy', targetCount: 14, genre: 'Pop' },
  { name: 'Hozier', targetCount: 20, genre: 'Rock' },
  { name: 'Måneskin', searchQuery: 'Maneskin', targetCount: 16, genre: 'Rock' },
  { name: 'Sam Fender', targetCount: 14, genre: 'Rock' },
  { name: 'The Neighbourhood', targetCount: 16, genre: 'Alternative' },
  { name: 'Wallows', targetCount: 12, genre: 'Rock' },
  { name: 'Dominic Fike', targetCount: 14, genre: 'Alternative' },
  { name: 'Phoebe Bridgers', targetCount: 14, genre: 'Alternative' },
  { name: 'boygenius', targetCount: 10, genre: 'Alternative' },
  { name: 'Lucy Dacus', targetCount: 8, genre: 'Alternative' },
  { name: 'Julien Baker', targetCount: 8, genre: 'Alternative' },
  { name: 'Mitski', targetCount: 16, genre: 'Alternative' },
  { name: 'Clairo', targetCount: 14, genre: 'Alternative' },
  { name: 'Beabadoobee', targetCount: 14, genre: 'Alternative' },
  { name: 'Mac DeMarco', targetCount: 14, genre: 'Alternative' },
  { name: 'Rex Orange County', targetCount: 14, genre: 'Alternative' },
  { name: 'Boy Pablo', targetCount: 10, genre: 'Alternative' },
  { name: 'Cavetown', targetCount: 12, genre: 'Alternative' },
  { name: 'Girl in Red', targetCount: 12, genre: 'Alternative' },
  { name: 'Declan McKenna', targetCount: 10, genre: 'Alternative' },
  { name: 'Inhaler', targetCount: 10, genre: 'Rock' },
  { name: 'Fontaines D.C.', searchQuery: 'Fontaines DC', targetCount: 12, genre: 'Rock' },
  { name: 'IDLES', targetCount: 12, genre: 'Rock' },
  { name: 'Amyl and the Sniffers', targetCount: 8, genre: 'Rock' },
  { name: 'Wet Leg', targetCount: 8, genre: 'Alternative' },
  { name: 'The Last Dinner Party', targetCount: 8, genre: 'Alternative' },
  { name: 'Bleachers', targetCount: 12, genre: 'Rock' },
  { name: 'fun.', searchQuery: 'fun', targetCount: 8, genre: 'Pop' },
  { name: 'Walk the Moon', targetCount: 8, genre: 'Rock' },
  { name: 'Bastille', targetCount: 18, genre: 'Rock' },
  { name: 'MGMT', targetCount: 14, genre: 'Alternative' },
  { name: 'Foster the People', targetCount: 14, genre: 'Alternative' },
  { name: 'Two Door Cinema Club', targetCount: 14, genre: 'Alternative' },
  { name: 'Phoenix', targetCount: 14, genre: 'Alternative' },
  { name: 'Vampire Weekend', targetCount: 18, genre: 'Alternative' },
  { name: 'Arcade Fire', targetCount: 18, genre: 'Alternative' },
  { name: 'The National', targetCount: 16, genre: 'Alternative' },
  { name: 'Bon Iver', targetCount: 16, genre: 'Alternative' },
  { name: 'Fleet Foxes', targetCount: 12, genre: 'Alternative' },
  { name: 'Iron & Wine', searchQuery: 'Iron and Wine', targetCount: 10, genre: 'Alternative' },
  { name: 'Sufjan Stevens', targetCount: 14, genre: 'Alternative' },
  { name: 'The Shins', targetCount: 12, genre: 'Alternative' },
  { name: 'Modest Mouse', targetCount: 14, genre: 'Alternative' },
  { name: 'Death Cab for Cutie', targetCount: 16, genre: 'Alternative' },
  { name: 'The Postal Service', targetCount: 8, genre: 'Alternative' },
  { name: 'The War on Drugs', targetCount: 12, genre: 'Alternative' },
  { name: 'Lord Huron', targetCount: 14, genre: 'Alternative' },
  { name: 'Of Monsters and Men', targetCount: 14, genre: 'Alternative' },
  { name: 'Young the Giant', targetCount: 14, genre: 'Rock' },
  { name: 'Grouplove', targetCount: 12, genre: 'Rock' },
  { name: 'Saint Motel', targetCount: 10, genre: 'Rock' },
  { name: 'Fitz and The Tantrums', targetCount: 12, genre: 'Pop' },
  { name: 'American Authors', targetCount: 8, genre: 'Pop' },
  { name: 'X Ambassadors', targetCount: 12, genre: 'Rock' },
  { name: 'Cold War Kids', targetCount: 12, genre: 'Rock' },
  { name: 'Portugal. The Man', searchQuery: 'Portugal The Man', targetCount: 12, genre: 'Rock' },
  { name: 'Milky Chance', targetCount: 12, genre: 'Alternative' },
  { name: 'Alt-J', searchQuery: 'Alt-J', targetCount: 14, genre: 'Alternative' },
  { name: 'Foals', targetCount: 14, genre: 'Alternative' },
  { name: 'Catfish and the Bottlemen', targetCount: 14, genre: 'Rock' },
  { name: 'Royal Blood', targetCount: 14, genre: 'Rock' },
  { name: 'Nothing But Thieves', targetCount: 14, genre: 'Rock' },
  { name: 'Wolf Alice', targetCount: 12, genre: 'Alternative' },
  { name: 'CHVRCHES', searchQuery: 'CHVRCHES', targetCount: 16, genre: 'Pop' },
  { name: 'Yeah Yeah Yeahs', targetCount: 14, genre: 'Alternative' },
  { name: 'Metric', targetCount: 14, genre: 'Alternative' },
  { name: 'Silversun Pickups', targetCount: 12, genre: 'Alternative' },
  { name: 'Grizzly Bear', targetCount: 10, genre: 'Alternative' },
  { name: 'Beach House', targetCount: 14, genre: 'Alternative' },
  { name: 'Cigarettes After Sex', targetCount: 14, genre: 'Alternative' },
  { name: 'Men I Trust', targetCount: 12, genre: 'Alternative' },
  { name: 'The Marías', searchQuery: 'The Marias', targetCount: 12, genre: 'Alternative' },
  { name: 'Cuco', targetCount: 12, genre: 'Alternative' },
  { name: 'Current Joys', targetCount: 10, genre: 'Alternative' },
  { name: 'Surf Curse', targetCount: 10, genre: 'Alternative' },
  { name: 'Vacations', targetCount: 8, genre: 'Alternative' },
  { name: 'TV Girl', targetCount: 12, genre: 'Alternative' },
  { name: 'Roar', targetCount: 6, genre: 'Alternative' },
  { name: 'Djo', targetCount: 8, genre: 'Alternative' },
  { name: 'Steve Lacy', targetCount: 14, genre: 'R&B/Soul' },
  { name: 'The Internet', targetCount: 12, genre: 'R&B/Soul' },
  { name: 'Thundercat', targetCount: 12, genre: 'R&B/Soul' },

  // ==========================================
  // 8. METAL / HARD ROCK / NU METAL / METALCORE
  // ==========================================
  { name: 'Metallica', targetCount: 30, genre: 'Metal' },
  { name: 'Iron Maiden', targetCount: 26, genre: 'Metal' },
  { name: 'Black Sabbath', targetCount: 25, genre: 'Metal' },
  { name: 'Ozzy Osbourne', targetCount: 22, genre: 'Metal' },
  { name: 'System of a Down', targetCount: 25, genre: 'Metal' },
  { name: 'Slipknot', targetCount: 25, genre: 'Metal' },
  { name: 'Korn', targetCount: 22, genre: 'Metal' },
  { name: 'Disturbed', targetCount: 22, genre: 'Metal' },
  { name: 'Avenged Sevenfold', targetCount: 22, genre: 'Metal' },
  { name: 'Deftones', targetCount: 22, genre: 'Metal' },
  { name: 'Rammstein', targetCount: 24, genre: 'Metal' },
  { name: 'Judas Priest', targetCount: 20, genre: 'Metal' },
  { name: 'Megadeth', targetCount: 20, genre: 'Metal' },
  { name: 'Slayer', targetCount: 18, genre: 'Metal' },
  { name: 'Pantera', targetCount: 20, genre: 'Metal' },
  { name: 'Motörhead', searchQuery: 'Motorhead', targetCount: 18, genre: 'Metal' },
  { name: 'Mötley Crüe', searchQuery: 'Motley Crue', targetCount: 20, genre: 'Metal' },
  { name: 'Ghost', targetCount: 18, genre: 'Metal' },
  { name: 'Bring Me The Horizon', targetCount: 25, genre: 'Rock' },
  { name: 'Bad Omens', targetCount: 14, genre: 'Metal' },
  { name: 'Sleep Token', targetCount: 14, genre: 'Metal' },
  { name: 'Falling In Reverse', targetCount: 16, genre: 'Rock' },
  { name: 'Pierce The Veil', targetCount: 14, genre: 'Rock' },
  { name: 'Sleeping With Sirens', targetCount: 12, genre: 'Rock' },
  { name: 'Asking Alexandria', targetCount: 14, genre: 'Metal' },
  { name: 'Bullet For My Valentine', targetCount: 16, genre: 'Metal' },
  { name: 'Killswitch Engage', targetCount: 14, genre: 'Metal' },
  { name: 'Trivium', targetCount: 14, genre: 'Metal' },
  { name: 'Five Finger Death Punch', targetCount: 18, genre: 'Metal' },
  { name: 'Shinedown', targetCount: 18, genre: 'Rock' },
  { name: 'Godsmack', targetCount: 16, genre: 'Rock' },
  { name: 'Seether', targetCount: 16, genre: 'Rock' },
  { name: 'Staind', targetCount: 14, genre: 'Rock' },
  { name: 'Puddle of Mudd', targetCount: 10, genre: 'Rock' },
  { name: 'Saliva', targetCount: 10, genre: 'Rock' },
  { name: 'Drowning Pool', targetCount: 8, genre: 'Metal' },
  { name: 'Mudvayne', targetCount: 10, genre: 'Metal' },
  { name: 'Static-X', targetCount: 10, genre: 'Metal' },
  { name: 'Coal Chamber', targetCount: 8, genre: 'Metal' },
  { name: 'Sepultura', targetCount: 12, genre: 'Metal' },
  { name: 'Soulfly', targetCount: 10, genre: 'Metal' },
  { name: 'Mastodon', targetCount: 14, genre: 'Metal' },
  { name: 'Gojira', targetCount: 14, genre: 'Metal' },
  { name: 'Lamb of God', targetCount: 14, genre: 'Metal' },
  { name: 'In Flames', targetCount: 14, genre: 'Metal' },
  { name: 'Nightwish', targetCount: 16, genre: 'Metal' },
  { name: 'Within Temptation', targetCount: 14, genre: 'Metal' },
  { name: 'Evanescence', targetCount: 20, genre: 'Rock' },
  { name: 'Lacuna Coil', targetCount: 12, genre: 'Metal' },
  { name: 'Arch Enemy', targetCount: 12, genre: 'Metal' },
  { name: 'Amon Amarth', targetCount: 12, genre: 'Metal' },
  { name: 'Children of Bodom', targetCount: 12, genre: 'Metal' },
  { name: 'Dimmu Borgir', targetCount: 10, genre: 'Metal' },
  { name: 'Cradle of Filth', targetCount: 10, genre: 'Metal' },
  { name: 'Behemoth', targetCount: 10, genre: 'Metal' },
  { name: 'Cannibal Corpse', targetCount: 8, genre: 'Metal' },
  { name: 'Scorpions', targetCount: 18, genre: 'Rock' },
  { name: 'Alice Cooper', targetCount: 18, genre: 'Rock' },
  { name: 'Twisted Sister', targetCount: 8, genre: 'Rock' },
  { name: 'Quiet Riot', targetCount: 8, genre: 'Rock' },
  { name: 'Dokken', targetCount: 10, genre: 'Rock' },
  { name: 'Warrant', targetCount: 8, genre: 'Rock' },
  { name: 'Poison', targetCount: 14, genre: 'Rock' },
  { name: 'Skid Row', targetCount: 12, genre: 'Rock' },
  { name: 'Cinderella', targetCount: 10, genre: 'Rock' },
  { name: 'Ratt', targetCount: 10, genre: 'Rock' },
  { name: 'Whitesnake', targetCount: 14, genre: 'Rock' },
  { name: 'Dio', targetCount: 12, genre: 'Metal' },
  { name: 'Rainbow', targetCount: 10, genre: 'Rock' },

  // ==========================================
  // 9. COUNTRY / SINGER-SONGWRITER / CROSSOVERS
  // ==========================================
  { name: 'Morgan Wallen', targetCount: 28, genre: 'Country' },
  { name: 'Luke Combs', targetCount: 25, genre: 'Country' },
  { name: 'Zach Bryan', targetCount: 26, genre: 'Country' },
  { name: 'Chris Stapleton', targetCount: 20, genre: 'Country' },
  { name: 'Kacey Musgraves', targetCount: 16, genre: 'Country' },
  { name: 'Dolly Parton', targetCount: 24, genre: 'Country' },
  { name: 'Johnny Cash', targetCount: 26, genre: 'Country' },
  { name: 'Willie Nelson', targetCount: 18, genre: 'Country' },
  { name: 'Shania Twain', targetCount: 24, genre: 'Country' },
  { name: 'Garth Brooks', targetCount: 16, genre: 'Country' },
  { name: 'Keith Urban', targetCount: 18, genre: 'Country' },
  { name: 'Carrie Underwood', targetCount: 24, genre: 'Country' },
  { name: 'Blake Shelton', targetCount: 18, genre: 'Country' },
  { name: 'Florida Georgia Line', targetCount: 18, genre: 'Country' },
  { name: 'Thomas Rhett', targetCount: 18, genre: 'Country' },
  { name: 'Kane Brown', targetCount: 18, genre: 'Country' },
  { name: 'Jelly Roll', targetCount: 18, genre: 'Country' },
  { name: 'Tyler Childers', targetCount: 14, genre: 'Country' },
  { name: 'Bailey Zimmerman', targetCount: 12, genre: 'Country' },
  { name: 'Lainey Wilson', targetCount: 14, genre: 'Country' },
  { name: 'Sam Hunt', targetCount: 14, genre: 'Country' },
  { name: 'Kelsea Ballerini', targetCount: 14, genre: 'Country' },
  { name: 'Dan + Shay', searchQuery: 'Dan and Shay', targetCount: 14, genre: 'Country' },
  { name: 'Rascal Flatts', targetCount: 16, genre: 'Country' },
  { name: 'Kenny Chesney', targetCount: 18, genre: 'Country' },
  { name: 'Tim McGraw', targetCount: 22, genre: 'Country' },
  { name: 'Zac Brown Band', targetCount: 16, genre: 'Country' },
  { name: 'Lady A', searchQuery: 'Lady Antebellum', targetCount: 14, genre: 'Country' },
  { name: 'The Chicks', searchQuery: 'Dixie Chicks', targetCount: 14, genre: 'Country' },
  { name: 'Miranda Lambert', targetCount: 16, genre: 'Country' },
  { name: 'Luke Bryan', targetCount: 20, genre: 'Country' },
  { name: 'Jason Aldean', targetCount: 20, genre: 'Country' },
  { name: 'Eric Church', targetCount: 18, genre: 'Country' },
  { name: 'Brad Paisley', targetCount: 18, genre: 'Country' },
  { name: 'Darius Rucker', targetCount: 14, genre: 'Country' },
  { name: 'Hootie & the Blowfish', targetCount: 12, genre: 'Rock' },
  { name: 'John Mayer', targetCount: 22, genre: 'Pop' },
  { name: 'Jack Johnson', targetCount: 16, genre: 'Pop' },
  { name: 'Jason Mraz', targetCount: 14, genre: 'Pop' },
  { name: 'Colbie Caillat', targetCount: 12, genre: 'Pop' },
  { name: 'Sara Bareilles', targetCount: 12, genre: 'Pop' },
  { name: 'Norah Jones', targetCount: 16, genre: 'Pop' },
  { name: 'James Morrison', targetCount: 10, genre: 'Pop' },
  { name: 'James Blunt', targetCount: 12, genre: 'Pop' },
  { name: 'Paolo Nutini', targetCount: 12, genre: 'Pop' },
  { name: 'Damien Rice', targetCount: 10, genre: 'Alternative' },
  { name: 'Passenger', targetCount: 10, genre: 'Pop' }
];

import { ARTIST_UNIVERSE_EXTENSION } from './artistUniverseExtension';

// Clean duplicates
const universeMap = new Map<string, UniverseArtist>();
for (const a of [...ARTIST_UNIVERSE, ...ARTIST_UNIVERSE_EXTENSION]) {
  const k = a.name.toLowerCase().trim();
  if (!universeMap.has(k)) {
    universeMap.set(k, a);
  }
}

export const UNIQUE_ARTIST_UNIVERSE = Array.from(universeMap.values());
