export interface CuratedHitQuery {
  artist: string;
  title: string;
  year: number;
  genre: string;
}

export const CURATED_EXPANSION_HITS: CuratedHitQuery[] = [
  // Pop Classics & 2010s/2020s smashes
  { artist: 'Gotye', title: 'Somebody That I Used to Know', year: 2011, genre: 'Pop' },
  { artist: 'fun.', title: 'We Are Young', year: 2011, genre: 'Pop' },
  { artist: 'fun.', title: 'Some Nights', year: 2012, genre: 'Pop' },
  { artist: 'MAGIC!', title: 'Rude', year: 2013, genre: 'Pop' },
  { artist: 'OMI', title: 'Cheerleader (Felix Jaehn Remix)', year: 2014, genre: 'Pop' },
  { artist: 'Walk the Moon', title: 'Shut Up and Dance', year: 2014, genre: 'Pop' },
  { artist: 'Rachel Platten', title: 'Fight Song', year: 2015, genre: 'Pop' },
  { artist: 'Andy Grammer', title: 'Honey, I\'m Good.', year: 2014, genre: 'Pop' },
  { artist: 'Lukas Graham', title: '7 Years', year: 2015, genre: 'Pop' },
  { artist: 'James Arthur', title: 'Say You Won\'t Let Go', year: 2016, genre: 'Pop' },
  { artist: 'Calum Scott', title: 'Dancing On My Own', year: 2016, genre: 'Pop' },
  { artist: 'Dean Lewis', title: 'Be Alright', year: 2018, genre: 'Pop' },
  { artist: 'Lewis Capaldi', title: 'Someone You Loved', year: 2018, genre: 'Pop' },
  { artist: 'Lewis Capaldi', title: 'Before You Go', year: 2019, genre: 'Pop' },
  { artist: 'Tones and I', title: 'Dance Monkey', year: 2019, genre: 'Pop' },
  { artist: 'Glass Animals', title: 'Heat Waves', year: 2020, genre: 'Alternative' },
  { artist: 'GAYLE', title: 'abcdefu', year: 2021, genre: 'Pop' },
  { artist: 'Stephen Sanchez', title: 'Until I Found You', year: 2021, genre: 'Pop' },
  { artist: 'Teddy Swims', title: 'Lose Control', year: 2023, genre: 'Pop' },
  { artist: 'Teddy Swims', title: 'The Door', year: 2024, genre: 'Pop' },
  { artist: 'Benson Boone', title: 'Beautiful Things', year: 2024, genre: 'Pop' },
  { artist: 'Benson Boone', title: 'Slow It Down', year: 2024, genre: 'Pop' },
  { artist: 'Hozier', title: 'Too Sweet', year: 2024, genre: 'Rock' },
  { artist: 'Shaboozey', title: 'A Bar Song (Tipsy)', year: 2024, genre: 'Country' },
  { artist: 'Noah Kahan', title: 'Stick Season', year: 2022, genre: 'Alternative' },
  { artist: 'Noah Kahan', title: 'Dial Drunk', year: 2023, genre: 'Alternative' },
  { artist: 'Zach Bryan', title: 'Something in the Orange', year: 2022, genre: 'Country' },
  { artist: 'Zach Bryan', title: 'I Remember Everything', year: 2023, genre: 'Country' },
  { artist: 'Zach Bryan', title: 'Pink Skies', year: 2024, genre: 'Country' },
  { artist: 'Morgan Wallen', title: 'Last Night', year: 2023, genre: 'Country' },
  { artist: 'Morgan Wallen', title: 'Wasted On You', year: 2021, genre: 'Country' },
  { artist: 'Morgan Wallen', title: 'Whiskey Glasses', year: 2018, genre: 'Country' },
  { artist: 'Morgan Wallen', title: 'You Proof', year: 2022, genre: 'Country' },
  { artist: 'Luke Combs', title: 'Fast Car', year: 2023, genre: 'Country' },
  { artist: 'Luke Combs', title: 'Beautiful Crazy', year: 2018, genre: 'Country' },
  { artist: 'Luke Combs', title: 'Beer Never Broke My Heart', year: 2019, genre: 'Country' },
  { artist: 'Luke Combs', title: 'Forever After All', year: 2020, genre: 'Country' },

  // Dance / Electronic anthems
  { artist: 'Bicep', title: 'Glue', year: 2017, genre: 'Electronic' },
  { artist: 'Disclosure', title: 'Latch', year: 2012, genre: 'Dance' },
  { artist: 'Disclosure', title: 'Omen', year: 2015, genre: 'Dance' },
  { artist: 'Duke Dumont', title: 'Ocean Drive', year: 2015, genre: 'Dance' },
  { artist: 'Duke Dumont', title: 'I Got U', year: 2014, genre: 'Dance' },
  { artist: 'Route 94', title: 'My Love', year: 2014, genre: 'Dance' },
  { artist: 'Gorgon City', title: 'Ready for Your Love', year: 2014, genre: 'Dance' },
  { artist: 'Kiesza', title: 'Hideaway', year: 2014, genre: 'Dance' },
  { artist: 'Oliver Heldens', title: 'Gecko (Overdrive)', year: 2014, genre: 'Dance' },
  { artist: 'Sigala', title: 'Easy Love', year: 2015, genre: 'Dance' },
  { artist: 'Jax Jones', title: 'You Don\'t Know Me', year: 2016, genre: 'Dance' },
  { artist: 'Jax Jones', title: 'Breathe', year: 2017, genre: 'Dance' },
  { artist: 'CamelPhat', title: 'Cola', year: 2017, genre: 'Dance' },
  { artist: 'CamelPhat', title: 'Panic Room', year: 2018, genre: 'Dance' },
  { artist: 'Regard', title: 'Ride It', year: 2019, genre: 'Dance' },
  { artist: 'Regard', title: 'Secrets', year: 2020, genre: 'Dance' },
  { artist: 'Joel Corry', title: 'Head & Heart', year: 2020, genre: 'Dance' },
  { artist: 'Joel Corry', title: 'BED', year: 2021, genre: 'Dance' },
  { artist: 'Acraze', title: 'Do It To It', year: 2021, genre: 'Dance' },
  { artist: 'LF SYSTEM', title: 'Afraid To Feel', year: 2022, genre: 'Dance' },
  { artist: 'Eliza Rose', title: 'B.O.T.A. (Baddest Of Them All)', year: 2022, genre: 'Dance' },
  { artist: 'Mau P', title: 'Drugs From Amsterdam', year: 2022, genre: 'Dance' },
  { artist: 'John Summit', title: 'Where You Are', year: 2023, genre: 'Dance' },
  { artist: 'John Summit', title: 'Shiver', year: 2024, genre: 'Dance' },
  { artist: 'Dom Dolla', title: 'Rhyme Dust', year: 2023, genre: 'Dance' },
  { artist: 'Dom Dolla', title: 'Saving Up', year: 2023, genre: 'Dance' },
  { artist: 'Peggy Gou', title: '(It Goes Like) Nanana', year: 2023, genre: 'Dance' },
  { artist: 'Fred again..', title: 'Marea (we\'ve lost dancing)', year: 2021, genre: 'Dance' },
  { artist: 'Fred again..', title: 'Delilah (pull me out of this)', year: 2022, genre: 'Dance' },
  { artist: 'Fred again..', title: 'Danielle (smile on my face)', year: 2022, genre: 'Dance' },
  { artist: 'Fred again..', title: 'adore u', year: 2023, genre: 'Dance' },
  { artist: 'Fred again..', title: 'leavemealone', year: 2023, genre: 'Dance' },

  // Hip-Hop / Rap viral & classic hits
  { artist: 'Sheck Wes', title: 'Mo Bamba', year: 2017, genre: 'Hip-Hop/Rap' },
  { artist: 'Desiigner', title: 'Panda', year: 2015, genre: 'Hip-Hop/Rap' },
  { artist: 'Desiigner', title: 'Tiimmy Turner', year: 2016, genre: 'Hip-Hop/Rap' },
  { artist: 'Rob $tone', title: 'Chill Bill', year: 2015, genre: 'Hip-Hop/Rap' },
  { artist: 'Dae Dae', title: 'Wat U Mean (Aye, Aye, Aye)', year: 2016, genre: 'Hip-Hop/Rap' },
  { artist: 'MadeinTYO', title: 'Uber Everywhere', year: 2016, genre: 'Hip-Hop/Rap' },
  { artist: 'MadeinTYO', title: 'Skateboard P', year: 2016, genre: 'Hip-Hop/Rap' },
  { artist: 'Ugly God', title: 'Water', year: 2016, genre: 'Hip-Hop/Rap' },
  { artist: 'Kyle', title: 'iSpy', year: 2016, genre: 'Hip-Hop/Rap' },
  { artist: 'Amine', title: 'Caroline', year: 2016, genre: 'Hip-Hop/Rap' },
  { artist: 'Amine', title: 'REEL IT IN', year: 2018, genre: 'Hip-Hop/Rap' },
  { artist: 'DRAM', title: 'Broccoli', year: 2016, genre: 'Hip-Hop/Rap' },
  { artist: 'DRAM', title: 'Cha Cha', year: 2015, genre: 'Hip-Hop/Rap' },
  { artist: 'GoldLink', title: 'Crew', year: 2016, genre: 'Hip-Hop/Rap' },
  { artist: 'YBN Nahmir', title: 'Rubbin Off the Paint', year: 2017, genre: 'Hip-Hop/Rap' },
  { artist: 'YBN Nahmir', title: 'Bounce Out With That', year: 2018, genre: 'Hip-Hop/Rap' },
  { artist: 'YBN Cordae', title: 'Kung Fu', year: 2018, genre: 'Hip-Hop/Rap' },
  { artist: 'YBN Cordae', title: 'Have Mercy', year: 2019, genre: 'Hip-Hop/Rap' },
  { artist: 'YBN Cordae', title: 'RNP', year: 2019, genre: 'Hip-Hop/Rap' },
  { artist: 'BlocBoy JB', title: 'Look Alive', year: 2018, genre: 'Hip-Hop/Rap' },
  { artist: 'BlocBoy JB', title: 'Rover 2.0', year: 2018, genre: 'Hip-Hop/Rap' },
  { artist: 'Lil Xan', title: 'Betrayed', year: 2017, genre: 'Hip-Hop/Rap' },
  { artist: 'Smokepurpp', title: 'Audi.', year: 2017, genre: 'Hip-Hop/Rap' },
  { artist: 'Smokepurpp', title: 'Fingers Blue', year: 2017, genre: 'Hip-Hop/Rap' },
  { artist: 'Comethazine', title: 'Bands', year: 2018, genre: 'Hip-Hop/Rap' },
  { artist: 'Comethazine', title: 'Walk', year: 2018, genre: 'Hip-Hop/Rap' },
  { artist: 'Blueface', title: 'Thotiana', year: 2018, genre: 'Hip-Hop/Rap' },
  { artist: 'Calboy', title: 'Envy Me', year: 2018, genre: 'Hip-Hop/Rap' },
  { artist: 'NLE Choppa', title: 'Shotta Flow', year: 2019, genre: 'Hip-Hop/Rap' },
  { artist: 'NLE Choppa', title: 'Camelot', year: 2019, genre: 'Hip-Hop/Rap' },
  { artist: 'NLE Choppa', title: 'Walk Em Down', year: 2020, genre: 'Hip-Hop/Rap' },
  { artist: 'NLE Choppa', title: 'Slut Me Out', year: 2022, genre: 'Hip-Hop/Rap' },
  { artist: 'StaySolidRocky', title: 'Party Girl', year: 2020, genre: 'Hip-Hop/Rap' },
  { artist: 'CJ', title: 'Whoopty', year: 2020, genre: 'Hip-Hop/Rap' },
  { artist: 'SpotemGottem', title: 'Beat Box', year: 2020, genre: 'Hip-Hop/Rap' },
  { artist: 'Pooh Shiesty', title: 'Back in Blood', year: 2020, genre: 'Hip-Hop/Rap' },
  { artist: 'Coi Leray', title: 'No More Parties', year: 2021, genre: 'Hip-Hop/Rap' },
  { artist: 'Coi Leray', title: 'Players', year: 2022, genre: 'Hip-Hop/Rap' },
  { artist: 'Ice Spice', title: 'Munch (Feelin\' U)', year: 2022, genre: 'Hip-Hop/Rap' },
  { artist: 'Ice Spice', title: 'In Ha Mood', year: 2023, genre: 'Hip-Hop/Rap' },
  { artist: 'Ice Spice', title: 'Princess Diana', year: 2023, genre: 'Hip-Hop/Rap' },
  { artist: 'Ice Spice', title: 'Deli', year: 2023, genre: 'Hip-Hop/Rap' },
  { artist: 'Sexyy Red', title: 'Pound Town', year: 2023, genre: 'Hip-Hop/Rap' },
  { artist: 'Sexyy Red', title: 'SkeeYee', year: 2023, genre: 'Hip-Hop/Rap' },
  { artist: 'Sexyy Red', title: 'Get It Sexyy', year: 2024, genre: 'Hip-Hop/Rap' },
  { artist: 'Tommy Richman', title: 'MILLION DOLLAR BABY', year: 2024, genre: 'R&B' },
  { artist: 'Tommy Richman', title: 'DEVIL IS A LIE', year: 2024, genre: 'R&B' },
];
