export interface SeedArtist {
  name: string;
  searchQuery?: string;
  tier: 1 | 2 | 3 | 4; // 1: 15-25, 2: 8-15, 3: 4-8, 4: 1-4
  targetCount: number;
  primaryDecade?: 'pre2000' | '2000s' | '2010s' | '2020s';
  primaryGenre?: string;
}

const RAW_ARTISTS: SeedArtist[] = [
  // ==========================================
  // 1. SOUNDCLOUD & EMO RAP ERA (Priority depth)
  // ==========================================
  { name: 'Lil Peep', tier: 2, targetCount: 15, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Lil Skies', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Juice WRLD', tier: 1, targetCount: 24, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'XXXTentacion', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Post Malone', tier: 1, targetCount: 24, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Trippie Redd', tier: 2, targetCount: 15, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Ski Mask the Slump God', searchQuery: 'Ski Mask The Slump God', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'YNW Melly', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Lil Pump', tier: 3, targetCount: 8, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Lil Uzi Vert', tier: 1, targetCount: 22, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Playboi Carti', tier: 1, targetCount: 16, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: '$uicideboy$', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: '6ix9ine', tier: 3, targetCount: 8, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Smokepurpp', tier: 4, targetCount: 4, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Iann Dior', tier: 3, targetCount: 8, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Trevor Daniel', tier: 4, targetCount: 4, primaryDecade: '2020s', primaryGenre: 'Pop' },
  { name: 'Yung Lean', tier: 3, targetCount: 8, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Tay-K', tier: 4, targetCount: 4, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Rich Brian', tier: 3, targetCount: 8, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },

  // ==========================================
  // 2. HIP-HOP / RAP (Golden Era, 2000s, Modern, UK)
  // ==========================================
  { name: '2Pac', tier: 1, targetCount: 22, primaryDecade: 'pre2000', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'The Notorious B.I.G.', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Dr. Dre', tier: 1, targetCount: 16, primaryDecade: 'pre2000', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Snoop Dogg', tier: 1, targetCount: 22, primaryDecade: 'pre2000', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Nas', tier: 1, targetCount: 20, primaryDecade: 'pre2000', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Wu-Tang Clan', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Jay-Z', tier: 1, targetCount: 24, primaryDecade: '2000s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Eminem', tier: 1, targetCount: 25, primaryDecade: '2000s', primaryGenre: 'Hip-Hop/Rap' },
  { name: '50 Cent', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Kanye West', tier: 1, targetCount: 25, primaryDecade: '2000s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Lil Wayne', tier: 1, targetCount: 24, primaryDecade: '2000s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'T.I.', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Nelly', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Outkast', tier: 1, targetCount: 18, primaryDecade: '2000s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Ludacris', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'DMX', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Ice Cube', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Bone Thugs-N-Harmony', searchQuery: 'Bone Thugs N Harmony', tier: 3, targetCount: 8, primaryDecade: 'pre2000', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Mobb Deep', tier: 3, targetCount: 8, primaryDecade: 'pre2000', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Big Pun', tier: 4, targetCount: 4, primaryDecade: 'pre2000', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Fugees', tier: 3, targetCount: 8, primaryDecade: 'pre2000', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Lauryn Hill', tier: 2, targetCount: 10, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Cypress Hill', tier: 3, targetCount: 8, primaryDecade: 'pre2000', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Warren G', tier: 3, targetCount: 6, primaryDecade: 'pre2000', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Coolio', tier: 3, targetCount: 5, primaryDecade: 'pre2000', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Busta Rhymes', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'A Tribe Called Quest', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Missy Elliott', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'LL Cool J', tier: 2, targetCount: 10, primaryDecade: 'pre2000', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Ja Rule', tier: 3, targetCount: 8, primaryDecade: '2000s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Fat Joe', tier: 3, targetCount: 8, primaryDecade: '2000s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'The Game', tier: 3, targetCount: 8, primaryDecade: '2000s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Cam\'ron', tier: 3, targetCount: 6, primaryDecade: '2000s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Kid Cudi', tier: 1, targetCount: 18, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Drake', tier: 1, targetCount: 25, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Nicki Minaj', tier: 1, targetCount: 24, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'J. Cole', tier: 1, targetCount: 22, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Kendrick Lamar', tier: 1, targetCount: 24, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Future', tier: 1, targetCount: 24, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Young Thug', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Travis Scott', tier: 1, targetCount: 24, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: '21 Savage', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Migos', tier: 1, targetCount: 18, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Quavo', tier: 3, targetCount: 8, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Offset', tier: 3, targetCount: 8, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Cardi B', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Megan Thee Stallion', tier: 2, targetCount: 14, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Lil Baby', tier: 1, targetCount: 20, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Gunna', tier: 2, targetCount: 15, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Roddy Ricch', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Polo G', tier: 2, targetCount: 14, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Lil Tjay', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Don Toliver', tier: 2, targetCount: 15, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Chief Keef', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Denzel Curry', tier: 3, targetCount: 8, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Kodak Black', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'A Boogie wit da Hoodie', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'A$AP Rocky', searchQuery: 'ASAP Rocky', tier: 1, targetCount: 18, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'A$AP Ferg', searchQuery: 'ASAP Ferg', tier: 3, targetCount: 8, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Mac Miller', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Tyler, The Creator', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Childish Gambino', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Big Sean', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Wiz Khalifa', tier: 1, targetCount: 18, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'French Montana', tier: 3, targetCount: 8, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Tyga', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Rae Sremmurd', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Swae Lee', tier: 3, targetCount: 8, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Lil Yachty', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'DaBaby', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Jack Harlow', tier: 2, targetCount: 14, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Central Cee', tier: 2, targetCount: 14, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Dave', tier: 3, targetCount: 8, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Stormzy', tier: 3, targetCount: 8, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Skepta', tier: 3, targetCount: 8, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Pop Smoke', tier: 1, targetCount: 18, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'King Von', tier: 3, targetCount: 8, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Lil Durk', tier: 2, targetCount: 14, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'NLE Choppa', tier: 3, targetCount: 8, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Cordae', tier: 3, targetCount: 6, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Joey Bada$$', searchQuery: 'Joey Badass', tier: 3, targetCount: 8, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Logic', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'G-Eazy', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'NF', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Machine Gun Kelly', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Rock' },

  // ==========================================
  // 3. POP / MAINSTREAM (Legends to 2020s)
  // ==========================================
  { name: 'Michael Jackson', tier: 1, targetCount: 25, primaryDecade: 'pre2000', primaryGenre: 'Pop' },
  { name: 'Madonna', tier: 1, targetCount: 24, primaryDecade: 'pre2000', primaryGenre: 'Pop' },
  { name: 'Prince', tier: 1, targetCount: 20, primaryDecade: 'pre2000', primaryGenre: 'Pop' },
  { name: 'Whitney Houston', tier: 1, targetCount: 20, primaryDecade: 'pre2000', primaryGenre: 'Pop' },
  { name: 'George Michael', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Pop' },
  { name: 'Cyndi Lauper', tier: 2, targetCount: 10, primaryDecade: 'pre2000', primaryGenre: 'Pop' },
  { name: 'Janet Jackson', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Pop' },
  { name: 'Cher', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'Pop' },
  { name: 'Celine Dion', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Pop' },
  { name: 'Mariah Carey', tier: 1, targetCount: 24, primaryDecade: 'pre2000', primaryGenre: 'Pop' },
  { name: 'Elton John', tier: 1, targetCount: 24, primaryDecade: 'pre2000', primaryGenre: 'Pop' },
  { name: 'Phil Collins', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Pop' },
  { name: 'Tina Turner', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'Pop' },
  { name: 'ABBA', tier: 1, targetCount: 20, primaryDecade: 'pre2000', primaryGenre: 'Pop' },
  { name: 'Spice Girls', tier: 2, targetCount: 10, primaryDecade: 'pre2000', primaryGenre: 'Pop' },
  { name: 'Paula Abdul', tier: 3, targetCount: 6, primaryDecade: 'pre2000', primaryGenre: 'Pop' },
  { name: 'Kylie Minogue', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'Britney Spears', tier: 1, targetCount: 25, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'Christina Aguilera', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'Backstreet Boys', tier: 1, targetCount: 18, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: '*NSYNC', searchQuery: 'NSYNC', tier: 1, targetCount: 16, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'Beyoncé', tier: 1, targetCount: 25, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'Rihanna', tier: 1, targetCount: 25, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'Lady Gaga', tier: 1, targetCount: 25, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'Katy Perry', tier: 1, targetCount: 24, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Justin Timberlake', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'P!nk', searchQuery: 'Pink', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'Kelly Clarkson', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'Avril Lavigne', tier: 1, targetCount: 18, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'Nelly Furtado', tier: 2, targetCount: 12, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'Gwen Stefani', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'Black Eyed Peas', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'Fergie', tier: 3, targetCount: 8, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'Kesha', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Pitbull', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Maroon 5', tier: 1, targetCount: 22, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'OneRepublic', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Shakira', tier: 1, targetCount: 24, primaryDecade: '2000s', primaryGenre: 'Latin' },
  { name: 'Enrique Iglesias', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'Latin' },
  { name: 'Ricky Martin', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'Latin' },
  { name: 'Hilary Duff', tier: 3, targetCount: 6, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'JoJo', tier: 3, targetCount: 6, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'Natasha Bedingfield', tier: 3, targetCount: 6, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'Taio Cruz', tier: 3, targetCount: 6, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Jay Sean', tier: 3, targetCount: 6, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Bruno Mars', tier: 1, targetCount: 24, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Adele', tier: 1, targetCount: 22, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Taylor Swift', tier: 1, targetCount: 25, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Justin Bieber', tier: 1, targetCount: 25, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Ariana Grande', tier: 1, targetCount: 25, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'The Weeknd', tier: 1, targetCount: 25, primaryDecade: '2010s', primaryGenre: 'R&B/Soul' },
  { name: 'Ed Sheeran', tier: 1, targetCount: 24, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Sam Smith', tier: 1, targetCount: 18, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Shawn Mendes', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Camila Cabello', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Sia', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Lorde', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Selena Gomez', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Demi Lovato', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Ellie Goulding', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Halsey', tier: 2, targetCount: 16, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Charlie Puth', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Carly Rae Jepsen', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Meghan Trainor', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Zara Larsson', tier: 3, targetCount: 8, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Bebe Rexha', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Jason Derulo', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'One Direction', tier: 1, targetCount: 22, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Harry Styles', tier: 1, targetCount: 20, primaryDecade: '2020s', primaryGenre: 'Pop' },
  { name: 'ZAYN', tier: 2, targetCount: 10, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Niall Horan', tier: 3, targetCount: 8, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: '5 Seconds of Summer', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Lizzo', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Troye Sivan', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Pop' },
  { name: 'Lauv', tier: 3, targetCount: 8, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Alessia Cara', tier: 3, targetCount: 8, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Rita Ora', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Jessie J', tier: 2, targetCount: 10, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Little Mix', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Fifth Harmony', tier: 2, targetCount: 10, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'James Arthur', tier: 2, targetCount: 10, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Lewis Capaldi', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Pop' },
  { name: 'George Ezra', tier: 3, targetCount: 8, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Tom Odell', tier: 3, targetCount: 6, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Conan Gray', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Pop' },
  { name: 'Dua Lipa', tier: 1, targetCount: 24, primaryDecade: '2020s', primaryGenre: 'Pop' },
  { name: 'Billie Eilish', tier: 1, targetCount: 24, primaryDecade: '2020s', primaryGenre: 'Pop' },
  { name: 'Olivia Rodrigo', tier: 1, targetCount: 20, primaryDecade: '2020s', primaryGenre: 'Pop' },
  { name: 'Sabrina Carpenter', tier: 1, targetCount: 20, primaryDecade: '2020s', primaryGenre: 'Pop' },
  { name: 'Doja Cat', tier: 1, targetCount: 22, primaryDecade: '2020s', primaryGenre: 'Pop' },
  { name: 'Chappell Roan', tier: 2, targetCount: 14, primaryDecade: '2020s', primaryGenre: 'Pop' },
  { name: 'Charli XCX', tier: 1, targetCount: 20, primaryDecade: '2020s', primaryGenre: 'Pop' },
  { name: 'Tate McRae', tier: 2, targetCount: 14, primaryDecade: '2020s', primaryGenre: 'Pop' },
  { name: 'Gracie Abrams', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Pop' },
  { name: 'Benson Boone', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Pop' },
  { name: 'Teddy Swims', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Pop' },
  { name: 'The Kid LAROI', tier: 2, targetCount: 14, primaryDecade: '2020s', primaryGenre: 'Hip-Hop/Rap' },
  { name: 'Miley Cyrus', tier: 1, targetCount: 24, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Ava Max', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Pop' },
  { name: 'Madison Beer', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Pop' },
  { name: 'Raye', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Pop' },

  // ==========================================
  // 4. ROCK / ALTERNATIVE / METAL / INDIE / PUNK
  // ==========================================
  { name: 'Queen', tier: 1, targetCount: 25, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'The Beatles', tier: 1, targetCount: 25, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'The Rolling Stones', tier: 1, targetCount: 24, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'AC/DC', tier: 1, targetCount: 24, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Pink Floyd', tier: 1, targetCount: 20, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Led Zeppelin', tier: 1, targetCount: 22, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Fleetwood Mac', tier: 1, targetCount: 22, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'David Bowie', tier: 1, targetCount: 24, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Guns N\' Roses', searchQuery: 'Guns N Roses', tier: 1, targetCount: 22, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Aerosmith', tier: 1, targetCount: 20, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'The Who', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'The Doors', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Eagles', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Boston', tier: 3, targetCount: 8, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Deep Purple', tier: 2, targetCount: 10, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'KISS', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Journey', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Toto', tier: 2, targetCount: 10, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Dire Straits', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Bruce Springsteen', tier: 1, targetCount: 22, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Tom Petty', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Creedence Clearwater Revival', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Van Halen', tier: 1, targetCount: 20, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Def Leppard', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Bon Jovi', tier: 1, targetCount: 22, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'The Police', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'U2', tier: 1, targetCount: 24, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'The Clash', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'Punk' },
  { name: 'Ramones', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'Punk' },
  { name: 'Blondie', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'The Cure', tier: 1, targetCount: 20, primaryDecade: 'pre2000', primaryGenre: 'Alternative' },
  { name: 'Depeche Mode', tier: 1, targetCount: 20, primaryDecade: 'pre2000', primaryGenre: 'Alternative' },
  { name: 'New Order', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'Alternative' },
  { name: 'The Smiths', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Alternative' },
  { name: 'Joy Division', tier: 3, targetCount: 6, primaryDecade: 'pre2000', primaryGenre: 'Alternative' },
  { name: 'Nirvana', tier: 1, targetCount: 24, primaryDecade: 'pre2000', primaryGenre: 'Alternative' },
  { name: 'Pearl Jam', tier: 1, targetCount: 20, primaryDecade: 'pre2000', primaryGenre: 'Alternative' },
  { name: 'Soundgarden', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'Alternative' },
  { name: 'Alice in Chains', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Alternative' },
  { name: 'Stone Temple Pilots', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'Alternative' },
  { name: 'Smashing Pumpkins', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'Alternative' },
  { name: 'Red Hot Chili Peppers', tier: 1, targetCount: 25, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Oasis', tier: 1, targetCount: 22, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Radiohead', tier: 1, targetCount: 24, primaryDecade: '2000s', primaryGenre: 'Alternative' },
  { name: 'Green Day', tier: 1, targetCount: 25, primaryDecade: '2000s', primaryGenre: 'Punk' },
  { name: 'Weezer', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'The Offspring', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'Punk' },
  { name: 'Blur', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'The Cranberries', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'R.E.M.', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'No Doubt', tier: 2, targetCount: 12, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Foo Fighters', tier: 1, targetCount: 24, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Blink-182', searchQuery: 'Blink-182', tier: 1, targetCount: 22, primaryDecade: '2000s', primaryGenre: 'Punk' },
  { name: 'Sum 41', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'Punk' },
  { name: 'Good Charlotte', tier: 2, targetCount: 10, primaryDecade: '2000s', primaryGenre: 'Punk' },
  { name: 'Simple Plan', tier: 2, targetCount: 10, primaryDecade: '2000s', primaryGenre: 'Punk' },
  { name: 'Audioslave', tier: 2, targetCount: 10, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Rage Against the Machine', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Sublime', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'Alternative' },
  { name: 'Third Eye Blind', tier: 2, targetCount: 10, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Matchbox Twenty', tier: 2, targetCount: 12, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Goo Goo Dolls', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'Rock' },
  { name: 'Linkin Park', tier: 1, targetCount: 25, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'System of a Down', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'Metal' },
  { name: 'Evanescence', tier: 1, targetCount: 18, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Paramore', tier: 1, targetCount: 22, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Fall Out Boy', tier: 1, targetCount: 22, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'My Chemical Romance', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Panic! At The Disco', searchQuery: 'Panic At The Disco', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'Rock' },
  { name: 'The Killers', tier: 1, targetCount: 22, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Muse', tier: 1, targetCount: 22, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Arctic Monkeys', tier: 1, targetCount: 24, primaryDecade: '2010s', primaryGenre: 'Rock' },
  { name: 'Franz Ferdinand', tier: 2, targetCount: 10, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'The Strokes', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Gorillaz', tier: 1, targetCount: 22, primaryDecade: '2000s', primaryGenre: 'Alternative' },
  { name: 'Coldplay', tier: 1, targetCount: 25, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Kings of Leon', tier: 1, targetCount: 18, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'The White Stripes', tier: 1, targetCount: 18, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Nickelback', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Three Days Grace', tier: 1, targetCount: 18, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Breaking Benjamin', tier: 1, targetCount: 16, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Papa Roach', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Limp Bizkit', tier: 1, targetCount: 18, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Slipknot', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'Metal' },
  { name: 'Korn', tier: 1, targetCount: 18, primaryDecade: '2000s', primaryGenre: 'Metal' },
  { name: 'Disturbed', tier: 1, targetCount: 18, primaryDecade: '2000s', primaryGenre: 'Metal' },
  { name: 'Avenged Sevenfold', tier: 1, targetCount: 18, primaryDecade: '2000s', primaryGenre: 'Metal' },
  { name: 'Deftones', tier: 1, targetCount: 18, primaryDecade: '2000s', primaryGenre: 'Metal' },
  { name: 'Rise Against', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'Punk' },
  { name: 'Jimmy Eat World', tier: 2, targetCount: 10, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Yellowcard', tier: 3, targetCount: 8, primaryDecade: '2000s', primaryGenre: 'Punk' },
  { name: 'All Time Low', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Punk' },
  { name: 'The All-American Rejects', tier: 2, targetCount: 10, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Snow Patrol', tier: 2, targetCount: 12, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Keane', tier: 2, targetCount: 12, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'The Kooks', tier: 3, targetCount: 8, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Kasabian', tier: 2, targetCount: 12, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'MGMT', tier: 2, targetCount: 10, primaryDecade: '2000s', primaryGenre: 'Alternative' },
  { name: 'Foster the People', tier: 2, targetCount: 10, primaryDecade: '2010s', primaryGenre: 'Alternative' },
  { name: 'Two Door Cinema Club', tier: 2, targetCount: 10, primaryDecade: '2010s', primaryGenre: 'Alternative' },
  { name: 'Walk the Moon', tier: 3, targetCount: 6, primaryDecade: '2010s', primaryGenre: 'Rock' },
  { name: 'Bastille', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Rock' },
  { name: 'The 1975', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'Rock' },
  { name: 'Twenty One Pilots', tier: 1, targetCount: 24, primaryDecade: '2010s', primaryGenre: 'Rock' },
  { name: 'Imagine Dragons', tier: 1, targetCount: 25, primaryDecade: '2010s', primaryGenre: 'Rock' },
  { name: 'The Black Keys', tier: 1, targetCount: 18, primaryDecade: '2010s', primaryGenre: 'Rock' },
  { name: 'Cage The Elephant', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Rock' },
  { name: 'Glass Animals', tier: 2, targetCount: 14, primaryDecade: '2020s', primaryGenre: 'Alternative' },
  { name: 'Florence + The Machine', searchQuery: 'Florence and The Machine', tier: 1, targetCount: 18, primaryDecade: '2010s', primaryGenre: 'Alternative' },
  { name: 'Mumford & Sons', searchQuery: 'Mumford and Sons', tier: 1, targetCount: 18, primaryDecade: '2010s', primaryGenre: 'Rock' },
  { name: 'The Lumineers', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Rock' },
  { name: 'Vance Joy', tier: 2, targetCount: 10, primaryDecade: '2010s', primaryGenre: 'Pop' },
  { name: 'Hozier', tier: 1, targetCount: 18, primaryDecade: '2010s', primaryGenre: 'Rock' },
  { name: 'Måneskin', searchQuery: 'Maneskin', tier: 2, targetCount: 14, primaryDecade: '2020s', primaryGenre: 'Rock' },
  { name: 'Sam Fender', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Rock' },
  { name: 'The Neighbourhood', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Alternative' },
  { name: 'Wallows', tier: 3, targetCount: 8, primaryDecade: '2020s', primaryGenre: 'Rock' },
  { name: 'Dominic Fike', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Alternative' },
  { name: 'Phoebe Bridgers', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Alternative' },
  { name: 'Mitski', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Alternative' },
  { name: 'Clairo', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Alternative' },
  { name: 'Tame Impala', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'Alternative' },
  { name: 'Metallica', tier: 1, targetCount: 25, primaryDecade: 'pre2000', primaryGenre: 'Metal' },
  { name: 'Iron Maiden', tier: 1, targetCount: 22, primaryDecade: 'pre2000', primaryGenre: 'Metal' },
  { name: 'Black Sabbath', tier: 1, targetCount: 20, primaryDecade: 'pre2000', primaryGenre: 'Metal' },
  { name: 'Judas Priest', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Metal' },
  { name: 'Megadeth', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Metal' },
  { name: 'Slayer', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'Metal' },
  { name: 'Pantera', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Metal' },
  { name: 'Ozzy Osbourne', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'Metal' },
  { name: 'Motörhead', searchQuery: 'Motorhead', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'Metal' },
  { name: 'Mötley Crüe', searchQuery: 'Motley Crue', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Metal' },
  { name: 'Rammstein', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'Metal' },
  { name: 'Ghost', tier: 2, targetCount: 14, primaryDecade: '2020s', primaryGenre: 'Metal' },
  { name: 'Bring Me The Horizon', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'Rock' },
  { name: 'Bad Omens', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Metal' },
  { name: 'Sleep Token', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Metal' },
  { name: 'Falling In Reverse', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Rock' },
  { name: 'Pierce The Veil', tier: 2, targetCount: 10, primaryDecade: '2010s', primaryGenre: 'Rock' },
  { name: 'Five Finger Death Punch', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Metal' },
  { name: 'Shinedown', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Rock' },
  { name: 'Godsmack', tier: 2, targetCount: 12, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Seether', tier: 2, targetCount: 12, primaryDecade: '2000s', primaryGenre: 'Rock' },
  { name: 'Hoobastank', tier: 3, targetCount: 6, primaryDecade: '2000s', primaryGenre: 'Rock' },

  // ==========================================
  // 5. ELECTRONIC / EDM / DANCE / HOUSE
  // ==========================================
  { name: 'Daft Punk', tier: 1, targetCount: 24, primaryDecade: '2000s', primaryGenre: 'Dance' },
  { name: 'The Prodigy', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'Dance' },
  { name: 'Fatboy Slim', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Dance' },
  { name: 'The Chemical Brothers', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Dance' },
  { name: 'Faithless', tier: 2, targetCount: 10, primaryDecade: 'pre2000', primaryGenre: 'Dance' },
  { name: 'Moby', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'Dance' },
  { name: 'Tiësto', searchQuery: 'Tiesto', tier: 1, targetCount: 22, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Armin van Buuren', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'ATB', tier: 3, targetCount: 8, primaryDecade: '2000s', primaryGenre: 'Dance' },
  { name: 'Darude', tier: 4, targetCount: 4, primaryDecade: '2000s', primaryGenre: 'Dance' },
  { name: 'Alice Deejay', tier: 4, targetCount: 4, primaryDecade: '2000s', primaryGenre: 'Dance' },
  { name: 'Cascada', tier: 2, targetCount: 10, primaryDecade: '2000s', primaryGenre: 'Dance' },
  { name: 'Basshunter', tier: 3, targetCount: 6, primaryDecade: '2000s', primaryGenre: 'Dance' },
  { name: 'Benny Benassi', tier: 3, targetCount: 6, primaryDecade: '2000s', primaryGenre: 'Dance' },
  { name: 'Eric Prydz', tier: 2, targetCount: 10, primaryDecade: '2000s', primaryGenre: 'Dance' },
  { name: 'David Guetta', tier: 1, targetCount: 25, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Calvin Harris', tier: 1, targetCount: 25, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Avicii', tier: 1, targetCount: 25, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Swedish House Mafia', tier: 1, targetCount: 18, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Skrillex', tier: 1, targetCount: 22, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Deadmau5', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Martin Garrix', tier: 1, targetCount: 22, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Zedd', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Kygo', tier: 1, targetCount: 22, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Marshmello', tier: 1, targetCount: 22, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Major Lazer', tier: 1, targetCount: 18, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'DJ Snake', tier: 1, targetCount: 18, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'The Chainsmokers', tier: 1, targetCount: 22, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Alesso', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Afrojack', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Steve Aoki', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Galantis', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Alan Walker', tier: 1, targetCount: 18, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Robin Schulz', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Lost Frequencies', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Jonas Blue', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Disclosure', tier: 1, targetCount: 18, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Flume', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'ODESZA', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'RÜFÜS DU SOL', searchQuery: 'Rufus Du Sol', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Dance' },
  { name: 'Fred again..', searchQuery: 'Fred again', tier: 1, targetCount: 18, primaryDecade: '2020s', primaryGenre: 'Dance' },
  { name: 'Fisher', tier: 3, targetCount: 8, primaryDecade: '2020s', primaryGenre: 'Dance' },
  { name: 'Peggy Gou', tier: 3, targetCount: 6, primaryDecade: '2020s', primaryGenre: 'Dance' },
  { name: 'Dom Dolla', tier: 3, targetCount: 8, primaryDecade: '2020s', primaryGenre: 'Dance' },
  { name: 'John Summit', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Dance' },
  { name: 'Meduza', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Dance' },
  { name: 'Jax Jones', tier: 2, targetCount: 10, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Joel Corry', tier: 3, targetCount: 8, primaryDecade: '2020s', primaryGenre: 'Dance' },
  { name: 'Oliver Heldens', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Dance' },
  { name: 'Hardwell', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Dance' },

  // ==========================================
  // 6. R&B / SOUL / FUNK / DISCO
  // ==========================================
  { name: 'Stevie Wonder', tier: 1, targetCount: 24, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Earth, Wind & Fire', searchQuery: 'Earth Wind and Fire', tier: 1, targetCount: 20, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Marvin Gaye', tier: 1, targetCount: 20, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Aretha Franklin', tier: 1, targetCount: 20, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Otis Redding', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Al Green', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Bill Withers', tier: 2, targetCount: 10, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Kool & The Gang', searchQuery: 'Kool and The Gang', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Donna Summer', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Bee Gees', tier: 1, targetCount: 22, primaryDecade: 'pre2000', primaryGenre: 'Pop' },
  { name: 'CHIC', tier: 2, targetCount: 10, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Sister Sledge', tier: 3, targetCount: 6, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Rick James', tier: 3, targetCount: 8, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Lionel Richie', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Sade', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Chaka Khan', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Luther Vandross', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Barry White', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'James Brown', tier: 1, targetCount: 20, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'The Temptations', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'The Supremes', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'The Isley Brothers', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Usher', tier: 1, targetCount: 25, primaryDecade: '2000s', primaryGenre: 'R&B/Soul' },
  { name: 'Aaliyah', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'TLC', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Destiny\'s Child', searchQuery: 'Destinys Child', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'R&B/Soul' },
  { name: 'Alicia Keys', tier: 1, targetCount: 24, primaryDecade: '2000s', primaryGenre: 'R&B/Soul' },
  { name: 'Ne-Yo', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'R&B/Soul' },
  { name: 'Chris Brown', tier: 1, targetCount: 25, primaryDecade: '2000s', primaryGenre: 'R&B/Soul' },
  { name: 'Boyz II Men', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Mary J. Blige', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'R&B/Soul' },
  { name: 'Brandy', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Monica', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Toni Braxton', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Ginuwine', tier: 3, targetCount: 8, primaryDecade: '2000s', primaryGenre: 'R&B/Soul' },
  { name: 'Craig David', tier: 2, targetCount: 12, primaryDecade: '2000s', primaryGenre: 'R&B/Soul' },
  { name: 'Mario', tier: 3, targetCount: 8, primaryDecade: '2000s', primaryGenre: 'R&B/Soul' },
  { name: 'Ciara', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'R&B/Soul' },
  { name: 'Trey Songz', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'R&B/Soul' },
  { name: 'Keyshia Cole', tier: 3, targetCount: 8, primaryDecade: '2000s', primaryGenre: 'R&B/Soul' },
  { name: 'Ashanti', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'R&B/Soul' },
  { name: 'John Legend', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'R&B/Soul' },
  { name: 'Amy Winehouse', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'R&B/Soul' },
  { name: 'Erykah Badu', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'R&B/Soul' },
  { name: 'Frank Ocean', tier: 1, targetCount: 22, primaryDecade: '2010s', primaryGenre: 'R&B/Soul' },
  { name: 'SZA', tier: 1, targetCount: 24, primaryDecade: '2020s', primaryGenre: 'R&B/Soul' },
  { name: 'Bryson Tiller', tier: 2, targetCount: 15, primaryDecade: '2010s', primaryGenre: 'R&B/Soul' },
  { name: 'PARTYNEXTDOOR', tier: 2, targetCount: 15, primaryDecade: '2010s', primaryGenre: 'R&B/Soul' },
  { name: 'Jhené Aiko', searchQuery: 'Jhene Aiko', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'R&B/Soul' },
  { name: 'Kehlani', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'R&B/Soul' },
  { name: 'Summer Walker', tier: 2, targetCount: 14, primaryDecade: '2020s', primaryGenre: 'R&B/Soul' },
  { name: 'Brent Faiyaz', tier: 2, targetCount: 15, primaryDecade: '2020s', primaryGenre: 'R&B/Soul' },
  { name: 'Giveon', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'R&B/Soul' },
  { name: 'Daniel Caesar', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'R&B/Soul' },
  { name: 'H.E.R.', searchQuery: 'H.E.R.', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'R&B/Soul' },
  { name: 'Khalid', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'R&B/Soul' },
  { name: 'Miguel', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'R&B/Soul' },
  { name: 'Tory Lanez', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Hip-Hop/Rap' },
  { name: '6LACK', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'R&B/Soul' },
  { name: 'Kali Uchis', tier: 2, targetCount: 14, primaryDecade: '2020s', primaryGenre: 'R&B/Soul' },
  { name: 'Jorja Smith', tier: 2, targetCount: 10, primaryDecade: '2010s', primaryGenre: 'R&B/Soul' },
  { name: 'Ella Mai', tier: 2, targetCount: 10, primaryDecade: '2010s', primaryGenre: 'R&B/Soul' },
  { name: 'T-Pain', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'R&B/Soul' },
  { name: 'Sean Kingston', tier: 2, targetCount: 10, primaryDecade: '2000s', primaryGenre: 'Pop' },
  { name: 'Sean Paul', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'Reggae' },
  { name: 'Shaggy', tier: 2, targetCount: 12, primaryDecade: '2000s', primaryGenre: 'Reggae' },

  // ==========================================
  // 7. LATIN / REGGAETON / REGIONAL MEXICAN
  // ==========================================
  { name: 'Daddy Yankee', tier: 1, targetCount: 24, primaryDecade: '2000s', primaryGenre: 'Latin' },
  { name: 'Don Omar', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'Latin' },
  { name: 'Wisin & Yandel', searchQuery: 'Wisin y Yandel', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'Latin' },
  { name: 'Tego Calderón', searchQuery: 'Tego Calderon', tier: 2, targetCount: 12, primaryDecade: '2000s', primaryGenre: 'Latin' },
  { name: 'Calle 13', tier: 2, targetCount: 12, primaryDecade: '2000s', primaryGenre: 'Latin' },
  { name: 'Zion & Lennox', searchQuery: 'Zion y Lennox', tier: 2, targetCount: 12, primaryDecade: '2000s', primaryGenre: 'Latin' },
  { name: 'Ivy Queen', tier: 3, targetCount: 8, primaryDecade: '2000s', primaryGenre: 'Latin' },
  { name: 'Plan B', tier: 2, targetCount: 10, primaryDecade: '2010s', primaryGenre: 'Latin' },
  { name: 'Bad Bunny', tier: 1, targetCount: 25, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'J Balvin', tier: 1, targetCount: 24, primaryDecade: '2010s', primaryGenre: 'Latin' },
  { name: 'Ozuna', tier: 1, targetCount: 24, primaryDecade: '2010s', primaryGenre: 'Latin' },
  { name: 'Anuel AA', tier: 1, targetCount: 22, primaryDecade: '2010s', primaryGenre: 'Latin' },
  { name: 'Karol G', tier: 1, targetCount: 24, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'Rauw Alejandro', tier: 1, targetCount: 22, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'Feid', tier: 1, targetCount: 20, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'Myke Towers', tier: 1, targetCount: 20, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'Quevedo', tier: 2, targetCount: 15, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'Rosalía', searchQuery: 'Rosalia', tier: 1, targetCount: 20, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'Maluma', tier: 1, targetCount: 22, primaryDecade: '2010s', primaryGenre: 'Latin' },
  { name: 'Nicky Jam', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'Latin' },
  { name: 'Farruko', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'Latin' },
  { name: 'Sech', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'Jhayco', searchQuery: 'Jhay Cortez', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'Mora', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'Manuel Turizo', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'Sebastián Yatra', searchQuery: 'Sebastian Yatra', tier: 2, targetCount: 14, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'Camilo', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'Luis Fonsi', tier: 1, targetCount: 18, primaryDecade: '2010s', primaryGenre: 'Latin' },
  { name: 'Romeo Santos', tier: 1, targetCount: 20, primaryDecade: '2010s', primaryGenre: 'Latin' },
  { name: 'Aventura', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'Latin' },
  { name: 'Prince Royce', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Latin' },
  { name: 'Natti Natasha', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Latin' },
  { name: 'Becky G', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Latin' },
  { name: 'Anitta', tier: 2, targetCount: 14, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'Arcángel', searchQuery: 'Arcangel', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Latin' },
  { name: 'Duki', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'Bizarrap', tier: 1, targetCount: 18, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'Maria Becerra', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'Nicki Nicole', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'Young Miko', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Latin' },
  { name: 'Peso Pluma', tier: 1, targetCount: 20, primaryDecade: '2020s', primaryGenre: 'Regional Mexican' },
  { name: 'Natanael Cano', tier: 1, targetCount: 18, primaryDecade: '2020s', primaryGenre: 'Regional Mexican' },
  { name: 'Fuerza Regida', tier: 1, targetCount: 18, primaryDecade: '2020s', primaryGenre: 'Regional Mexican' },
  { name: 'Junior H', tier: 1, targetCount: 18, primaryDecade: '2020s', primaryGenre: 'Regional Mexican' },
  { name: 'Grupo Frontera', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Regional Mexican' },
  { name: 'Eslabon Armado', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Regional Mexican' },
  { name: 'Carin Leon', tier: 1, targetCount: 16, primaryDecade: '2020s', primaryGenre: 'Regional Mexican' },
  { name: 'Christian Nodal', tier: 1, targetCount: 16, primaryDecade: '2020s', primaryGenre: 'Regional Mexican' },
  { name: 'Grupo Firme', tier: 2, targetCount: 12, primaryDecade: '2020s', primaryGenre: 'Regional Mexican' },
  { name: 'Banda MS', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Regional Mexican' },
  { name: 'Selena', tier: 1, targetCount: 18, primaryDecade: 'pre2000', primaryGenre: 'Latin' },
  { name: 'Juanes', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'Latin' },
  { name: 'Maná', searchQuery: 'Mana', tier: 1, targetCount: 18, primaryDecade: '2000s', primaryGenre: 'Latin' },

  // ==========================================
  // 8. COUNTRY / FOLK / SINGER-SONGWRITER
  // ==========================================
  { name: 'Morgan Wallen', tier: 1, targetCount: 24, primaryDecade: '2020s', primaryGenre: 'Country' },
  { name: 'Luke Combs', tier: 1, targetCount: 22, primaryDecade: '2020s', primaryGenre: 'Country' },
  { name: 'Chris Stapleton', tier: 1, targetCount: 18, primaryDecade: '2010s', primaryGenre: 'Country' },
  { name: 'Zach Bryan', tier: 1, targetCount: 22, primaryDecade: '2020s', primaryGenre: 'Country' },
  { name: 'Kacey Musgraves', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Country' },
  { name: 'Dolly Parton', tier: 1, targetCount: 20, primaryDecade: 'pre2000', primaryGenre: 'Country' },
  { name: 'Johnny Cash', tier: 1, targetCount: 22, primaryDecade: 'pre2000', primaryGenre: 'Country' },
  { name: 'Willie Nelson', tier: 2, targetCount: 14, primaryDecade: 'pre2000', primaryGenre: 'Country' },
  { name: 'Shania Twain', tier: 1, targetCount: 20, primaryDecade: 'pre2000', primaryGenre: 'Country' },
  { name: 'Garth Brooks', tier: 2, targetCount: 12, primaryDecade: 'pre2000', primaryGenre: 'Country' },
  { name: 'Keith Urban', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'Country' },
  { name: 'Carrie Underwood', tier: 1, targetCount: 20, primaryDecade: '2000s', primaryGenre: 'Country' },
  { name: 'Blake Shelton', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Country' },
  { name: 'Florida Georgia Line', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Country' },
  { name: 'Thomas Rhett', tier: 2, targetCount: 14, primaryDecade: '2010s', primaryGenre: 'Country' },
  { name: 'Kane Brown', tier: 2, targetCount: 14, primaryDecade: '2020s', primaryGenre: 'Country' },
  { name: 'Jelly Roll', tier: 2, targetCount: 14, primaryDecade: '2020s', primaryGenre: 'Country' },
  { name: 'Noah Kahan', tier: 2, targetCount: 14, primaryDecade: '2020s', primaryGenre: 'Country' },
  { name: 'Tyler Childers', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Country' },
  { name: 'Bailey Zimmerman', tier: 3, targetCount: 8, primaryDecade: '2020s', primaryGenre: 'Country' },
  { name: 'Lainey Wilson', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Country' },
  { name: 'Sam Hunt', tier: 2, targetCount: 10, primaryDecade: '2010s', primaryGenre: 'Country' },
  { name: 'Kelsea Ballerini', tier: 2, targetCount: 10, primaryDecade: '2020s', primaryGenre: 'Country' },
  { name: 'Dan + Shay', searchQuery: 'Dan and Shay', tier: 2, targetCount: 10, primaryDecade: '2010s', primaryGenre: 'Country' },
  { name: 'Rascal Flatts', tier: 2, targetCount: 12, primaryDecade: '2000s', primaryGenre: 'Country' },
  { name: 'Kenny Chesney', tier: 2, targetCount: 14, primaryDecade: '2000s', primaryGenre: 'Country' },
  { name: 'Tim McGraw', tier: 1, targetCount: 18, primaryDecade: '2000s', primaryGenre: 'Country' },
  { name: 'Zac Brown Band', tier: 2, targetCount: 12, primaryDecade: '2010s', primaryGenre: 'Country' },
];

// Ensure unique by normalized name
const seen = new Set<string>();
export const SEED_ARTISTS: SeedArtist[] = RAW_ARTISTS.filter((a) => {
  const norm = a.name.toLowerCase().trim();
  if (seen.has(norm)) return false;
  seen.add(norm);
  return true;
});
